/**
 * Seed Function
 * (sails.config.bootstrap)
 *
 * A function that runs just before your Sails app gets lifted.
 * > Need more flexibility?  You can also create a hook.
 *
 * For more information on seeding your app with fake data, check out:
 * https://sailsjs.com/config/bootstrap
 */

module.exports.bootstrap = async function () {

  // Import dependencies
  var path = require('path');
  var moment = require('moment');

  // This bootstrap version indicates what version of fake data we're dealing with here.
  var HARD_CODED_DATA_VERSION = 4;

  // This path indicates where to store/look for the JSON file that tracks the "last run bootstrap info"
  // locally on this development computer (if we happen to be on a development computer).
  var bootstrapLastRunInfoPath = path.resolve(sails.config.appPath, '.tmp/bootstrap-version.json');

  // Whether or not to continue doing the stuff in this file (i.e. wiping and regenerating data)
  // depends on some factors:
  // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  // If the hard-coded data version has been incremented, or we're being forced
  // (i.e. `--drop` or `--environment=test` was set), then run the meat of this
  // bootstrap script to wipe all existing data and rebuild hard-coded data.
  if (sails.config.models.migrate !== 'drop' && sails.config.environment !== 'test') {
    // If this is _actually_ a production environment (real or simulated), or we have
    // `migrate: safe` enabled, then prevent accidentally removing all data!
    if (process.env.NODE_ENV === 'production' || sails.config.models.migrate === 'safe') {
      sails.log('Так как мы работаем с миграцией: \'safe\' and/or NODE_ENV=production (in the "' + sails.config.environment + '" Sails, если быть точным), пропуская оставшуюся часть начальной загрузки, чтобы избежать потери данных...');
      return;
    }//•

    // Compare bootstrap version from code base to the version that was last run
    var lastRunBootstrapInfo = await sails.helpers.fs.readJson(bootstrapLastRunInfoPath)
      .tolerate('doesNotExist');// (it's ok if the file doesn't exist yet-- just keep going.)

    if (lastRunBootstrapInfo && lastRunBootstrapInfo.lastRunVersion === HARD_CODED_DATA_VERSION) {
      sails.log('Работает v' + HARD_CODED_DATA_VERSION + ' файла начальной загрузки (bootstrap.js)...  (because it\'s already been run)');
      sails.log('(последний запуск на этом компьютере: @ ' + (new Date(lastRunBootstrapInfo.lastRunAt)) + ')');
      return;
    }//•

    sails.log('Запуск v' + HARD_CODED_DATA_VERSION + ' bootstrap script...  (' + (lastRunBootstrapInfo ? 'before this, the last time the bootstrap ran on this computer was for v' + lastRunBootstrapInfo.lastRunVersion + ' @ ' + (new Date(lastRunBootstrapInfo.lastRunAt)) : 'looks like this is the first time the bootstrap has run on this computer') + ')');
  }
  else {
    sails.log('Запуск скрипта начальной загрузки, поскольку он был вынужден ...  (either `--drop` or `--environment=test` использовался)');
  }


  // Since the hard-coded data version has been incremented, and we're running in
  // a "throwaway data" environment, delete all records from all models.
  for (let identity in sails.models) {
    await sails.models[identity].destroy({});
  }//∞
  // By convention, this is a good place to set up fake data during development.
  // По общему мнению, это хорошее место для настройки поддельных данных во время разработки.
  let ryanDahl = await User.create(
    {
      emailAddress: sails.config.custom.friendEmailAddress,
      fullName: 'Ryan Dahl',
      isAdmin: false,
      avatar:sails.config.custom.avatar,
      password: await sails.helpers.passwords.hashPassword(sails.config.custom.passwordSuperAdmin),
      preferredLocale: 'en'
    }).fetch();

  let alexFox = await User.create({
    emailAddress: sails.config.custom.internalEmailAddress,
    fullName: 'Alex Fox',
    isAdmin: false,
    // getFullName: function(){return  `${this.fullName} ${this.emailAddress}`;},
    isSuperAdmin: true,
    preferredLocale: 'en',
    password: await sails.helpers.passwords.hashPassword(sails.config.custom.passwordSuperAdmin),
    gravatar: await sails.helpers.gravatar.getAvatarUrl(sails.config.custom.internalEmailAddress)
  }).fetch();

  let star = await User.create({
    emailAddress: 'vasef@mail.ru',
    fullName: 'Ольга Петрова',
    isAdmin: true,
    // getFullName: function(){return  `${this.fullName} ${this.emailAddress}`;},
    isSuperAdmin: false,
    preferredLocale: 'en',
    password: await sails.helpers.passwords.hashPassword(sails.config.custom.passwordSuperAdmin),
    gravatar: await sails.helpers.gravatar.getAvatarUrl('vasef@mail.ru')
  }).fetch();
  // console.log('alexFox::: ID' , alexFox);
  let adam = await User.create({
    emailAddress: 'administrator.f@mail.ru',
    fullName: 'Poale Ell Adam',
    isAdmin: false,
    preferredLocale: 'en',
    password: await sails.helpers.passwords.hashPassword(sails.config.custom.passwordSuperAdmin),
    gravatar: await sails.helpers.gravatar.getAvatarUrl(sails.config.custom.internalEmailAddress)
  }).fetch();

  let bob = await User.create({
    emailAddress: 'kremotory@mail.ru',
    fullName: 'Bob Scott',
    isAdmin: false,
    isSuperAdmin: true,
    preferredLocale: 'en',
    password: await sails.helpers.passwords.hashPassword(sails.config.custom.passwordSuperAdmin),
    gravatar: await sails.helpers.gravatar.getAvatarUrl(sails.config.custom.internalEmailAddress)
  }).fetch();

  // Добавить Райана Даля , как одного из друзей Алекса Фокса
  // и добавить Алекса Фокса в друзья Райану Далю
  await User.addToCollection(alexFox.id, 'friends', ryanDahl.id);
  await User.addToCollection(ryanDahl.id, 'friends', alexFox.id);

  // Создаём группу пользователей admin

  let group2 = await Group.create({
    label: 'user',
    whoCreate: alexFox.id,
    subtitle: 'user - группа по умолчанию для всех зарегистрированных и подтвердивших свой email пользователей. Чтение. Комментарии.'
  }).fetch();
  let group3 = await Group.create({label: 'owner', whoCreate: alexFox.id}).fetch();
  let group4 = await Group.create({label: 'breeder', whoCreate: alexFox.id}).fetch();
  let group = await Group.create({
    label: 'admin',
    whoCreate: alexFox.id,
    subtitle: 'admin - самая привилегированная группа пользователей сайта. Права на управление сайтом. Удаление, Изменение, Добавление, Обновление.',
  }).fetch();
  // Добавить пользователя alexFox.id в группу 'admin'
  await User.addToCollection(alexFox.id, 'groups', group.id);


  /* let continentEurasia = await Continent.create({
     label: 'Eurasia',
     labelRu: 'Евразия',
     whoCreate: alexFox.id,
     description: 'Евра́зия — самый большой материк на Земле, и единственный, омываемый четырьмя океанами: на юге — Индийским, на севере — Северным Ледовитым, на западе — Атлантическим, на востоке — Тихим. Континент расположен в Северном полушарии между 9° з. д. и 169° з. д., при этом часть островов Евразии находится в Южном полушарии.'
   }).fetch();


   let continentSouthAmerica = await Continent.create({
     label: 'South America',
     labelRu: 'Южная Америка',
     whoCreate: alexFox.id,
     description: 'Ю́жная Аме́рика — один из шести материков планеты Земля, расположенный на юге Западного полушария. Омывается на западе Тихим океаном, на востоке — Атлантическим, на севере — Карибским морем, которое является естественным рубежом между двумя Америками. Панамский перешеек на северо-западе материка соединяет Южную Америку с Северной.'
   }).fetch();


   let continentNorthAmerica = await Continent.create({
     label: 'North America',
     labelRu: 'Северная Америка',
     whoCreate: alexFox.id,
     description: 'Се́верная Аме́рика (англ. North America, фр. Amérique du Nord, исп. América del Norte, Norteamérica, аст. Ixachitlān Mictlāmpa) — один из шести материков планеты Земля, расположенный на севере Западного полушария Земли.'
   }).fetch();


   let continentAfrica = await Continent.create({
     label: 'Africa',
     labelRu: 'Африка',
     whoCreate: alexFox.id,
     description: 'А́фрика — второй по площади материк после Евразии, омывается Средиземным морем с севера, Красным — с северо-востока, Атлантическим океаном с запада и Индийским океаном с востока и юга. Африкой называется также часть света, состоящая из материка Африка и прилегающих островов. Площадь Африки без островов составляет 29,2 млн км², с островами — около 30,3 млн км²[3], покрывая, таким образом, 6 % общей площади поверхности Земли и 20,4 % поверхности суши. На территории Африки расположено 55 государств.'
   }).fetch();


   let continentAustralia = await Continent.create({
     label: 'Australia',
     labelRu: 'Австралия',
     whoCreate: alexFox.id,
     description: 'Австра́лия (от лат. australis — «южный») — континент, расположенный в Восточном и Южном полушариях Земли. Вся территория материка является основной частью государства Австралия. Материк входит в часть света Австралия и Океания. Самый маленький и сухой материк.'
   }).fetch();



   let arrCountryEurasia = [
     {label:'Abkhazia',labelRu:'Абхазия'},
     {label:'Austria',labelRu:'Австрия'},
     {label:'Azerbaijan',labelRu:'Азербайджан'},
     {label:'Albania',labelRu:'Албания'},
     {label:'Andorra',labelRu:'Андорра'},
     {label:'Armenia',labelRu:'Армения'},
     {label:'Afghanistan',labelRu:'Афганистан'},
     {label:'Bangladesh',labelRu:'Бангладеш'},
     {label:'Bahrain',labelRu:'Бахрейн'},
     {label:'Belarus',labelRu:'Белоруссия'},
     {label:'Belgium',labelRu:'Бельгия'},
     {label:'Bulgaria',labelRu:'Болгария'},
     {label:'Bosnia and Herzegovina',labelRu:'Босния и Герцеговина'},
     {label:'Brunei',labelRu:'Бруней'},
     {label:'Butane',labelRu:'Бутан'},
     {label:'Vatican',labelRu:'Ватикан'},
     {label:'Great Britain',labelRu:'Великобритания'},
     {label:'Hungary',labelRu:'Венгрия'},
     {label:'East Timor',labelRu:'Восточный Тимор'},
     {label:'Vietnam',labelRu:'Вьетнам'},
     {label:'Germany',labelRu:'Германия'},
     {label:'Greece',labelRu:'Греция'},
     {label:'Georgia',labelRu:'Грузия'},
     {label:'Denmark',labelRu:'Дания'},
     {label:'DNR',labelRu:'ДНР'},
     {label:'Egypt',labelRu:'Египет'},
     {label:'Israel',labelRu:'Израиль'},
     {label:'India',labelRu:'Индия'},
     {label:'Indonesia',labelRu:'Индонезия'},
     {label:'Jordan',labelRu:'Иордания'},
     {label:'Iraq',labelRu:'Ирак'},
     {label:'Iran',labelRu:'Иран'},
     {label:'Ireland',labelRu:'Ирландия'},
     {label:'Iceland',labelRu:'Исландия'},
     {label:'Spain',labelRu:'Испания'},
     {label:'Italy',labelRu:'Италия'},
     {label:'Yemen',labelRu:'Йемен'},
     {label:'Kazakhstan',labelRu:'Казахстан'},
     {label:'Cambodia',labelRu:'Камбоджа'},
     {label:'Qatar',labelRu:'Катар'},
     {label:'Cyprus',labelRu:'Кипр'},
     {label:'Kyrgyzstan',labelRu:'Киргизия'},
     {label:'China',labelRu:'Китай'},
     {label:'Republic of China',labelRu:'Китайская Республика'},
     {label:'DPRK',labelRu:'КНДР'},
     {label:'Kuwait',labelRu:'Кувейт'},
     {label:'Laos',labelRu:'Лаос'},
     {label:'Latvia',labelRu:'Латвия'},
     {label:'Lebanon',labelRu:'Ливан'},
     {label:'Lithuania',labelRu:'Литва'},
     {label:'Liechtenstein',labelRu:'Лихтенштейн'},
     {label:'LNR',labelRu:'ЛНР'},
     {label:'Luxembourg',labelRu:'Люксембург'},
     {label:'Malaysia',labelRu:'Малайзия'},
     {label:'Maldives',labelRu:'Мальдивы'},
     {label:'Malta',labelRu:'Мальта'},
     {label:'Moldova',labelRu:'Молдавия'},
     {label:'Monaco',labelRu:'Монако'},
     {label:'Mongolia',labelRu:'Монголия'},
     {label:'Myanmar',labelRu:'Мьянма'},
     {label:'NKR',labelRu:'НКР'},
     {label:'Nepal',labelRu:'Непал'},
     {label:'Netherlands',labelRu:'Нидерланды'},
     {label:'Norway',labelRu:'Норвегия'},
     {label:'UAE',labelRu:'ОАЭ'},
     {label:'Oman',labelRu:'Оман'},
     {label:'Pakistan',labelRu:'Пакистан'},
     {label:'State of Palestine',labelRu:'Государство Палестина'},
     {label:'Poland',labelRu:'Польша'},
     {label:'Portugal',labelRu:'Португалия'},
     {label:'Transnistria',labelRu:'Приднестровье'},
     {label:'The Republic of Korea',labelRu:'Республика Корея'},
     {label:'Republic of Kosovo',labelRu:'Республика Косово'},
     {label:'Russia',labelRu:'Россия'},
     {label:'Northern Macedonia',labelRu:'Северная Македония'},
     {label:'Romania',labelRu:'Румыния'},
     {label:'San Marino',labelRu:'Сан-Марино'},
     {label:'Saudi Arabia',labelRu:'Саудовская Аравия'},
     {label:'Northern Cyprus',labelRu:'Северный Кипр'},
     {label:'Serbia',labelRu:'Сербия'},
     {label:'Singapore',labelRu:'Сингапур'},
     {label:'Syria',labelRu:'Сирия'},
     {label:'Slovakia',labelRu:'Словакия'},
     {label:'Slovenia',labelRu:'Словения'},
     {label:'Tajikistan',labelRu:'Таджикистан'},
     {label:'Thailand',labelRu:'Таиланд'},
     {label:'Turkmenistan',labelRu:'Туркмения'},
     {label:'Turkey',labelRu:'Турция'},
     {label:'Uzbekistan',labelRu:'Узбекистан'},
     {label:'Ukraine',labelRu:'Украина'},
     {label:'Philippines',labelRu:'Филиппины'},
     {label:'Finland',labelRu:'Финляндия'},
     {label:'France',labelRu:'Франция'},
     {label:'Croatia',labelRu:'Хорватия'},
     {label:'Montenegro',labelRu:'Черногория'},
     {label:'Czech',labelRu:'Чехия'},
     {label:'Switzerland',labelRu:'Швейцария'},
     {label:'Sweden',labelRu:'Швеция'},
     {label:'Sri Lanka',labelRu:'Шри-Ланка'},
     {label:'Estonia',labelRu:'Эстония'},
     {label:'South Ossetia',labelRu:'Южная Осетия'},
     {label:'Japan',labelRu:'Япония'}];

   let copyEurasia =['Abkhazia',
 'Austria',
 'Azerbaijan',
 'Albania',
 'Andorra',
 'Armenia',
 'Afghanistan',
 'Bangladesh',
 'Bahrain',
 'Belarus',
 'Belgium',
 'Bulgaria',
 'Bosnia and Herzegovina',
 'Brunei',
 'Butane',
 'Vatican',
 'Great Britain',
 'Hungary',
 'East Timor',
 'Vietnam',
 'Germany',
 'Greece',
 'Georgia',
 'Denmark',
 'DNR',
 'Egypt',
 'Israel',
 'India',
 'Indonesia',
 'Jordan',
 'Iraq',
 'Iran',
 'Ireland',
 'Iceland',
 'Spain',
 'Italy',
 'Yemen',
 'Kazakhstan',
 'Cambodia',
 'Qatar',
 'Cyprus',
 'Kyrgyzstan',
 'China',
 'Republic of China',
 'DPRK',
 'Kuwait',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lithuania',
 'Liechtenstein',
 'LNR',
 'Luxembourg',
 'Malaysia',
 'Maldives',
 'Malta',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Myanmar',
 'NKR',
 'Nepal',
 'Netherlands',
 'Norway',
 'UAE',
 'Oman',
 'Pakistan',
 'State of Palestine',
 'Poland',
 'Portugal',
 'Transnistria',
 'The Republic of Korea',
 'Republic of Kosovo',
 'Russia',
 'Northern Macedonia',
 'Romania',
 'San Marino',
 'Saudi Arabia',
 'Northern Cyprus',
 'Serbia',
 'Singapore',
 'Syria',
 'Slovakia',
 'Slovenia',
 'Tajikistan',
 'Thailand',
 'Turkmenistan',
 'Turkey',
 'Uzbekistan',
 'Ukraine',
 'Philippines',
 'Finland',
 'France',
 'Croatia',
 'Montenegro',
 'Czech',
 'Switzerland',
 'Sweden',
 'Sri Lanka',
 'Estonia',
 'South Ossetia',
 'Japan'];


   let arrCountrySouthAmerica = [
     'Argentina',
     'Bolivia',
     'Brazil',
     'Venezuela',
     'Guyana',
     'Colombia',
     'Paraguay',
     'Peru',
     'Suriname',
     'Uruguay',
     'Chile',
     'Ecuador',
     'Falkland Islands (Malvinas)',
     'French Guiana',
     'South Georgia and the South Sandwich Islands'];
   let arrCountryNorthAmerica = [
     'Antigua and Barbuda',
     'Bahamas',
     'Barbados',
     'Belize',
     'Haiti',
     'Guatemala',
     'Honduras',
     'Grenada',
     'Dominica',
     'Dominican Republic',
     'Canada',
     'Costa Rica',
     'Cuba',
     'Mexico',
     'Nicaragua',
     'Panama',
     'Salvador',
     'Saint Lucia',
     'Saint Vincent and the Grenadines',
     'Saint Kitts and Nevis',
     'USA',
     'Trinidad and Tobago',
     'Jamaica'];
   let arrCountryAfrica = [
     'Algeria',
     'Angola',
     'Benin',
     'Botswana',
     'Burkina Fas',
     'Burundi',
     'Gabon',
     'Gambia',
     'Ghana',
     'Guinea',
     'Guinea-Bissau',
     'Djibouti',
     'Egipe',
     'Zambia',
     'Zimbabwe',
     'Cape Verde',
     'Cameroon',
     'Canary Islands',
     'Kenya',
     'Comoros',
     'Democratic Republic of the Congo',
     'Republic of Kong',
     'Côte d’Ivoire',
     'Lesotho',
     'Liberia',
     'Libya',
     'Mauritius',
     'Mauritania',
     'Madagascar',
     'Madeira',
     'Mayotte',
     'Malawi',
     'Mali',
     'Morocco',
     'Melil',
     'Mozambique',
     'Namibia',
     'Niger',
     'Nigeria',
     'Reuno',
     'Rwanda',
     'Sao Tome and Principe',
     'Sahara Arab Democratic Republics',
     'Swaziland',
     'Saint Helena, Ascension and Tristan da Cun',
     'Seychelles',
     'Senegal',
     'Ceut',
     'Somalia',
     'Somaliland',
     'Sudan',
     'Sierra Leone',
     'Tanzania',
     'Togo',
     'Tunisia',
     'Uganda',
     'CAR',
     'Chad',
     'Equatorial Guinea',
     'Eritrea',
     'Ethiopia',
     'South African Republic',
     'South Sudan'];
   let arrCountryAustralia = [
     'Australian Capital Territory',
     'Victoria',
     'Western Australia',
     'Queensland',
     'N.S.W',
     'Northern Territory',
     'Tasmania',
     'South Australia'
   ];

   arrCountryEurasia = await arrCountryEurasia.map(country => {
     return {
       label: country.label,
       labelRu: country.labelRu,
       whoCreate: alexFox.id,
       region: continentEurasia.id,
       description: 'Описание отсутствует.'
     };
   });

   arrCountrySouthAmerica = await arrCountrySouthAmerica.map(country => {
     return {
       label: country,
       whoCreate: alexFox.id,
       region: continentSouthAmerica.id,
       description: 'Описание отсутствует.'
     };
   });

   arrCountryNorthAmerica = await arrCountryNorthAmerica.map(country => {
     return {
       label: country,
       whoCreate: alexFox.id,
       region: continentNorthAmerica.id,
       description: 'Описание отсутствует.'
     };
   });

   arrCountryAfrica = await arrCountryAfrica.map(country => {
     return {
       label: country,
       whoCreate: alexFox.id,
       region: continentAfrica.id,
       description: 'Описание отсутствует.'
     };
   });

   arrCountryAustralia = await arrCountryAustralia.map(country => {
     return {
       label: country,
       whoCreate: alexFox.id,
       region: continentAustralia.id,
       description: 'Описание отсутствует.'
     };
   });


   let resCountryEurasia = await Country.createEach(arrCountryEurasia).fetch();

   let russia = await resCountryEurasia.filter(ctr => {
     return (ctr.label === 'Russia') ? ctr : '';
   });

   // console.log('russia', russia);
   // await _.each(cityList, city => {
   //   city.country =
   // });

   let arrCityListRussia = [
     {'value':'Abaza','labelRu':'Абаза'},
     {'value':'Abakan','labelRu':'Абакан'},
     {'value':'Abdulino','labelRu':'Абдулино'},
     {'value':'Abinsk','labelRu':'Абинск'},
     {'value':'Agidel','labelRu':'Агидель'},
     {'value':'Agryz','labelRu':'Агрыз'},
     {'value':'Adygeysk','labelRu':'Адыгейск'},
     {'value':'Aznakaevo','labelRu':'Азнакаево'},
     {'value':'Azov','labelRu':'Азов'},
     {'value':'Ak-Dovurak','labelRu':'Ак-Довурак'},
     {'value':'Aksay','labelRu':'Аксай'},
     {'value':'Alagir','labelRu':'Алагир'},
     {'value':'Alapaevsk','labelRu':'Алапаевск'},
     {'value':'Alatyr','labelRu':'Алатырь'},
     {'value':'Aldan','labelRu':'Алдан'},
     {'value':'Aleysk','labelRu':'Алейск'},
     {'value':'Alexandrov','labelRu':'Александров'},
     {'value':'Aleksandrovsk','labelRu':'Александровск'},
     {'value':'Aleksandrovsk-Sakhalinsky','labelRu':'Александровск-Сахалинский'},
     {'value':'Alekseyevka','labelRu':'Алексеевка'},
     {'value':'Aleksin','labelRu':'Алексин'},
     {'value':'Alzamay','labelRu':'Алзамай'},
     {'value':'Alupka','labelRu':'Алупка'},
     {'value':'Alushta','labelRu':'Алушта'},
     {'value':'Almetyevsk','labelRu':'Альметьевск'},
     {'value':'Amursk','labelRu':'Амурск'},
     {'value':'Anadyr','labelRu':'Анадырь'},
     {'value':'Anapa','labelRu':'Анапа'},
     {'value':'Angarsk','labelRu':'Ангарск'},
     {'value':'Andreapol','labelRu':'Андреаполь'},
     {'value':'Anzhero-Sudzhensk','labelRu':'Анжеро-Судженск'},
     {'value':'Aniva','labelRu':'Анива'},
     {'value':'Apatity','labelRu':'Апатиты'},
     {'value':'Aprelevka','labelRu':'Апрелевка'},
     {'value':'Apsheronsk','labelRu':'Апшеронск'},
     {'value':'Aramil','labelRu':'Арамиль'},
     {'value':'Argun','labelRu':'Аргун'},
     {'value':'Ardatov','labelRu':'Ардатов'},
     {'value':'Ardon','labelRu':'Ардон'},
     {'value':'Arzamas','labelRu':'Арзамас'},
     {'value':'Arkadak','labelRu':'Аркадак'},
     {'value':'Armavir','labelRu':'Армавир'},
     {'value':'Armyansk','labelRu':'Армянск'},
     {'value':'Arsenyev','labelRu':'Арсеньев'},
     {'value':'Arsk','labelRu':'Арск'},
     {'value':'Artyom','labelRu':'Артём'},
     {'value':'Artyomovsk','labelRu':'Артёмовск'},
     {'value':'Artyomovsky','labelRu':'Артёмовский'},
     {'value':'Arkhangelsk','labelRu':'Архангельск'},
     {'value':'Asbestos','labelRu':'Асбест'},
     {'value':'Asino','labelRu':'Асино'},
     {'value':'Astrakhan','labelRu':'Астрахань'},
     {'value':'Atkarsk','labelRu':'Аткарск'},
     {'value':'Akhtubinsk','labelRu':'Ахтубинск'},
     {'value':'Achinsk','labelRu':'Ачинск'},
     {'value':'Asha','labelRu':'Аша'},
     {'value':'Babaevo','labelRu':'Бабаево'},
     {'value':'Grandmas','labelRu':'Бабушкин'},
     {'value':'Bavly','labelRu':'Бавлы'},
     {'value':'Bagrationovsk','labelRu':'Багратионовск'},
     {'value':'Baykalsk','labelRu':'Байкальск'},
     {'value':'Baymak','labelRu':'Баймак'},
     {'value':'Bacal','labelRu':'Бакал'},
     {'value':'Baksan','labelRu':'Баксан'},
     {'value':'Balabanovo','labelRu':'Балабаново'},
     {'value':'Balakovo','labelRu':'Балаково'},
     {'value':'Balakhna','labelRu':'Балахна'},
     {'value':'Balashikha','labelRu':'Балашиха'},
     {'value':'Balashov','labelRu':'Балашов'},
     {'value':'Balay','labelRu':'Балей'},
     {'value':'Baltiysk','labelRu':'Балтийск'},
     {'value':'Barabinsk','labelRu':'Барабинск'},
     {'value':'Barnaul','labelRu':'Барнаул'},
     {'value':'Barysh','labelRu':'Барыш'},
     {'value':'Bataysk','labelRu':'Батайск'},
     {'value':'Bakhchisarai','labelRu':'Бахчисарай'},
     {'value':'Bezhetsk','labelRu':'Бежецк'},
     {'value':'Belaya Kalitva','labelRu':'Белая Калитва'},
     {'value':'White Kholunitsa','labelRu':'Белая Холуница'},
     {'value':'Belgorod','labelRu':'Белгород'},
     {'value':'Belebey','labelRu':'Белебей'},
     {'value':'Belev','labelRu':'Белёв'},
     {'value':'Belinsky','labelRu':'Белинский'},
     {'value':'Belovo','labelRu':'Белово'},
     {'value':'Belogorsk','labelRu':'Белогорск'},
     {'value':'Belogorsk','labelRu':'Белогорск'},
     {'value':'Belozersk','labelRu':'Белозерск'},
     {'value':'Belokurikha','labelRu':'Белокуриха'},
     {'value':'Belomorsk','labelRu':'Беломорск'},
     {'value':'Beloretsk','labelRu':'Белорецк'},
     {'value':'Belorechensk','labelRu':'Белореченск'},
     {'value':'Belousovo','labelRu':'Белоусово'},
     {'value':'Beloyarsky','labelRu':'Белоярский'},
     {'value':'White','labelRu':'Белый'},
     {'value':'Berdsk','labelRu':'Бердск'},
     {'value':'Berezniki','labelRu':'Березники'},
     {'value':'Berezovsky','labelRu':'Берёзовский'},
     {'value':'Berezovsky','labelRu':'Берёзовский'},
     {'value':'Beslan','labelRu':'Беслан'},
     {'value':'Biysk','labelRu':'Бийск'},
     {'value':'Bikin','labelRu':'Бикин'},
     {'value':'Bilibino','labelRu':'Билибино'},
     {'value':'Birobidzhan','labelRu':'Биробиджан'},
     {'value':'Birsk','labelRu':'Бирск'},
     {'value':'Biryusinsk','labelRu':'Бирюсинск'},
     {'value':'Biryuch','labelRu':'Бирюч'},
     {'value':'Blagoveshchensk','labelRu':'Благовещенск'},
     {'value':'Blagoveshchensk','labelRu':'Благовещенск'},
     {'value':'Grateful','labelRu':'Благодарный'},
     {'value':'Beavers','labelRu':'Бобров'},
     {'value':'Bogdanovich','labelRu':'Богданович'},
     {'value':'Bogoroditsk','labelRu':'Богородицк'},
     {'value':'Bogorodsk','labelRu':'Богородск'},
     {'value':'Bogotol','labelRu':'Боготол'},
     {'value':'Boguchar','labelRu':'Богучар'},
     {'value':'Bodaybo','labelRu':'Бодайбо'},
     {'value':'Boksitogorsk','labelRu':'Бокситогорск'},
     {'value':'Bulgarians','labelRu':'Болгар'},
     {'value':'Bologoye','labelRu':'Бологое'},
     {'value':'Marshland','labelRu':'Болотное'},
     {'value':'Bolokhovo','labelRu':'Болохово'},
     {'value':'Bolkhov','labelRu':'Болхов'},
     {'value':'Big Stone','labelRu':'Большой Камень'},
     {'value':'Boron','labelRu':'Бор'},
     {'value':'Borzya','labelRu':'Борзя'},
     {'value':'Borisoglebsk','labelRu':'Борисоглебск'},
     {'value':'Borovichi','labelRu':'Боровичи'},
     {'value':'Borovsk','labelRu':'Боровск'},
     {'value':'Borodino','labelRu':'Бородино'},
     {'value':'Bratsk','labelRu':'Братск'},
     {'value':'Bronnitsy','labelRu':'Бронницы'},
     {'value':'Bryansk','labelRu':'Брянск'},
     {'value':'Bugulma','labelRu':'Бугульма'},
     {'value':'Buguruslan','labelRu':'Бугуруслан'},
     {'value':'Budennovsk','labelRu':'Будённовск'},
     {'value':'Buzuluk','labelRu':'Бузулук'},
     {'value':'Buoy','labelRu':'Буй'},
     {'value':'Buynaksk','labelRu':'Буйнакск'},
     {'value':'Buinsk','labelRu':'Буинск'},
     {'value':'Buturlinovka','labelRu':'Бутурлиновка'},
     {'value':'Valdai','labelRu':'Валдай'},
     {'value':'Valuyki','labelRu':'Валуйки'},
     {'value':'Velizh','labelRu':'Велиж'},
     {'value':'Great Luke','labelRu':'Великие Луки'},
     {'value':'Velikiy Novgorod','labelRu':'Великий Новгород'},
     {'value':'Great Ustyug','labelRu':'Великий Устюг'},
     {'value':'Velsk','labelRu':'Вельск'},
     {'value':'Venev','labelRu':'Венёв'},
     {'value':'Vereshchagino','labelRu':'Верещагино'},
     {'value':'Vereya','labelRu':'Верея'},
     {'value':'Verkhneuralsk','labelRu':'Верхнеуральск'},
     {'value':'Upper Tagil','labelRu':'Верхний Тагил'},
     {'value':'Upper Ufaley','labelRu':'Верхний Уфалей'},
     {'value':'Upper Pyshma','labelRu':'Верхняя Пышма'},
     {'value':'Upper Salda','labelRu':'Верхняя Салда'},
     {'value':'Upper Tour','labelRu':'Верхняя Тура'},
     {'value':'Verkhoturye','labelRu':'Верхотурье'},
     {'value':'Verkhoyansk','labelRu':'Верхоянск'},
     {'value':'Vesegonsk','labelRu':'Весьегонск'},
     {'value':'Vetluga','labelRu':'Ветлуга'},
     {'value':'Prominent','labelRu':'Видное'},
     {'value':'Vilyuisk','labelRu':'Вилюйск'},
     {'value':'Vilyuchinsk','labelRu':'Вилючинск'},
     {'value':'Swallow','labelRu':'Вихоревка'},
     {'value':'Vichuga','labelRu':'Вичуга'},
     {'value':'Vladivostok','labelRu':'Владивосток'},
     {'value':'Vladikavkaz','labelRu':'Владикавказ'},
     {'value':'Vladimir','labelRu':'Владимир'},
     {'value':'Volgograd','labelRu':'Волгоград'},
     {'value':'Volgodonsk','labelRu':'Волгодонск'},
     {'value':'Volgorechensk','labelRu':'Волгореченск'},
     {'value':'Volzhsk','labelRu':'Волжск'},
     {'value':'Volzhsky','labelRu':'Волжский'},
     {'value':'Vologda','labelRu':'Вологда'},
     {'value':'Volodarsk','labelRu':'Володарск'},
     {'value':'Volokolamsk','labelRu':'Волоколамск'},
     {'value':'Volosovo','labelRu':'Волосово'},
     {'value':'Volkhov','labelRu':'Волхов'},
     {'value':'Volchansk','labelRu':'Волчанск'},
     {'value':'Volsk','labelRu':'Вольск'},
     {'value':'Vorkuta','labelRu':'Воркута'},
     {'value':'Voronezh','labelRu':'Воронеж'},
     {'value':'Vorsma','labelRu':'Ворсма'},
     {'value':'Voskresensk','labelRu':'Воскресенск'},
     {'value':'Votkinsk','labelRu':'Воткинск'},
     {'value':'Vsevolozhsk','labelRu':'Всеволожск'},
     {'value':'Vuktyl','labelRu':'Вуктыл'},
     {'value':'Vyborg','labelRu':'Выборг'},
     {'value':'Vyksa','labelRu':'Выкса'},
     {'value':'Vysokovsk','labelRu':'Высоковск'},
     {'value':'Vysotsk','labelRu':'Высоцк'},
     {'value':'Vytegra','labelRu':'Вытегра'},
     {'value':'Vyshny Volochyok','labelRu':'Вышний Волочёк'},
     {'value':'Vyazemsky','labelRu':'Вяземский'},
     {'value':'Vyazniki','labelRu':'Вязники'},
     {'value':'Vyazma','labelRu':'Вязьма'},
     {'value':'Vyatskiye Polyany','labelRu':'Вятские Поляны'},
     {'value':'Gavrilov Posad','labelRu':'Гаврилов Посад'},
     {'value':'Gavrilov-Yam','labelRu':'Гаврилов-Ям'},
     {'value':'Gagarin','labelRu':'Гагарин'},
     {'value':'Gadzhievo','labelRu':'Гаджиево'},
     {'value':'Guy','labelRu':'Гай'},
     {'value':'Galich','labelRu':'Галич'},
     {'value':'Gatchina','labelRu':'Гатчина'},
     {'value':'Guards','labelRu':'Гвардейск'},
     {'value':'Gdov','labelRu':'Гдов'},
     {'value':'Gelendzhik','labelRu':'Геленджик'},
     {'value':'Georgievsk','labelRu':'Георгиевск'},
     {'value':'Eyes','labelRu':'Глазов'},
     {'value':'Golitsyno','labelRu':'Голицыно'},
     {'value':'Gorbatov','labelRu':'Горбатов'},
     {'value':'Gorno-Altaisk','labelRu':'Горно-Алтайск'},
     {'value':'Gornozavodsk','labelRu':'Горнозаводск'},
     {'value':'Miner','labelRu':'Горняк'},
     {'value':'Gorodets','labelRu':'Городец'},
     {'value':'Hillfort','labelRu':'Городище'},
     {'value':'Gorodovikovsk','labelRu':'Городовиковск'},
     {'value':'Gorokhovets','labelRu':'Гороховец'},
     {'value':'Hot key','labelRu':'Горячий Ключ'},
     {'value':'Grayvoron','labelRu':'Грайворон'},
     {'value':'Gremyachinsk','labelRu':'Гремячинск'},
     {'value':'Grozny','labelRu':'Грозный'},
     {'value':'Mud','labelRu':'Грязи'},
     {'value':'Gryazovets','labelRu':'Грязовец'},
     {'value':'Gubaha','labelRu':'Губаха'},
     {'value':'Gubkin','labelRu':'Губкин'},
     {'value':'Gubkinsky','labelRu':'Губкинский'},
     {'value':'Gudermes','labelRu':'Гудермес'},
     {'value':'Gukovo','labelRu':'Гуково'},
     {'value':'Gulkevichi','labelRu':'Гулькевичи'},
     {'value':'Guryevsk','labelRu':'Гурьевск'},
     {'value':'Guryevsk','labelRu':'Гурьевск'},
     {'value':'Gusev','labelRu':'Гусев'},
     {'value':'Gusinoozersk','labelRu':'Гусиноозёрск'},
     {'value':'Gus-Crystal','labelRu':'Гусь-Хрустальный'},
     {'value':'Davlekanovo','labelRu':'Давлеканово'},
     {'value':'Dagestan Fires','labelRu':'Дагестанские Огни'},
     {'value':'Dalmatovo','labelRu':'Далматово'},
     {'value':'Dalnegorsk','labelRu':'Дальнегорск'},
     {'value':'Dalnerechensk','labelRu':'Дальнереченск'},
     {'value':'Danilov','labelRu':'Данилов'},
     {'value':'Dankov','labelRu':'Данков'},
     {'value':'Degtyarsk','labelRu':'Дегтярск'},
     {'value':'Dedovsk','labelRu':'Дедовск'},
     {'value':'Demidov','labelRu':'Демидов'},
     {'value':'Derbent','labelRu':'Дербент'},
     {'value':'Desnogorsk','labelRu':'Десногорск'},
     {'value':'Jankoy','labelRu':'Джанкой'},
     {'value':'Dzerzhinsk','labelRu':'Дзержинск'},
     {'value':'Dzerzhinsky','labelRu':'Дзержинский'},
     {'value':'Divnogorsk','labelRu':'Дивногорск'},
     {'value':'Digora','labelRu':'Дигора'},
     {'value':'Dimitrovgrad','labelRu':'Димитровград'},
     {'value':'Dmitriev','labelRu':'Дмитриев'},
     {'value':'Dmitrov','labelRu':'Дмитров'},
     {'value':'Dmitrovsk','labelRu':'Дмитровск'},
     {'value':'Bottom','labelRu':'Дно'},
     {'value':'Dobryanka','labelRu':'Добрянка'},
     {'value':'Dolgoprudny','labelRu':'Долгопрудный'},
     {'value':'Dolinsk','labelRu':'Долинск'},
     {'value':'Domodedovo','labelRu':'Домодедово'},
     {'value':'Donetsk','labelRu':'Донецк'},
     {'value':'Donskoy','labelRu':'Донской'},
     {'value':'Dorogobuzh','labelRu':'Дорогобуж'},
     {'value':'Drezna','labelRu':'Дрезна'},
     {'value':'Dubna','labelRu':'Дубна'},
     {'value':'Dubovka','labelRu':'Дубовка'},
     {'value':'Dudinka','labelRu':'Дудинка'},
     {'value':'Dukhovshchina','labelRu':'Духовщина'},
     {'value':'Dyurtyuli','labelRu':'Дюртюли'},
     {'value':'Dyatkovo','labelRu':'Дятьково'},
     {'value':'Evpatoria','labelRu':'Евпатория'},
     {'value':'Yegorievsk','labelRu':'Егорьевск'},
     {'value':'Yeisk','labelRu':'Ейск'},
     {'value':'Yekaterinburg','labelRu':'Екатеринбург'},
     {'value':'Yelabuga','labelRu':'Елабуга'},
     {'value':'Dace','labelRu':'Елец'},
     {'value':'Elizovo','labelRu':'Елизово'},
     {'value':'Yelnya','labelRu':'Ельня'},
     {'value':'Yemanzhelinsk','labelRu':'Еманжелинск'},
     {'value':'Emva','labelRu':'Емва'},
     {'value':'Yeniseisk','labelRu':'Енисейск'},
     {'value':'Yermolino','labelRu':'Ермолино'},
     {'value':'Ershov','labelRu':'Ершов'},
     {'value':'Essentuki','labelRu':'Ессентуки'},
     {'value':'Yefremov','labelRu':'Ефремов'},
     {'value':'Zheleznovodsk','labelRu':'Железноводск'},
     {'value':'Zheleznogorsk','labelRu':'Железногорск'},
     {'value':'Zheleznogorsk','labelRu':'Железногорск'},
     {'value':'Zheleznogorsk-Ilimsky','labelRu':'Железногорск-Илимский'},
     {'value':'Pervyevka','labelRu':'Жердевка'},
     {'value':'Zhigulevsk','labelRu':'Жигулёвск'},
     {'value':'Zhizdra','labelRu':'Жиздра'},
     {'value':'Zhirnovsk','labelRu':'Жирновск'},
     {'value':'Zhukov','labelRu':'Жуков'},
     {'value':'Zhukovka','labelRu':'Жуковка'},
     {'value':'Zhukovsky','labelRu':'Жуковский'},
     {'value':'Zavitinsk','labelRu':'Завитинск'},
     {'value':'Zavodoukovsk','labelRu':'Заводоуковск'},
     {'value':'Zavolzhsk','labelRu':'Заволжск'},
     {'value':'The Volga region','labelRu':'Заволжье'},
     {'value':'Zadonsk','labelRu':'Задонск'},
     {'value':'Zainsk','labelRu':'Заинск'},
     {'value':'Zakamensk','labelRu':'Закаменск'},
     {'value':'Zaozyorny','labelRu':'Заозёрный'},
     {'value':'Zaoersk','labelRu':'Заозёрск'},
     {'value':'Western Dvina','labelRu':'Западная Двина'},
     {'value':'Polar','labelRu':'Заполярный'},
     {'value':'Zaraysk','labelRu':'Зарайск'},
     {'value':'Zarechny','labelRu':'Заречный'},
     {'value':'Zarechny','labelRu':'Заречный'},
     {'value':'Zarinsk','labelRu':'Заринск'},
     {'value':'Zvenigovo','labelRu':'Звенигово'},
     {'value':'Zvenigorod','labelRu':'Звенигород'},
     {'value':'Zverevo','labelRu':'Зверево'},
     {'value':'Zelenogorsk','labelRu':'Зеленогорск'},
     {'value':'Zelenogradsk','labelRu':'Зеленоградск'},
     {'value':'Zelenodolsk','labelRu':'Зеленодольск'},
     {'value':'Zelenokumsk','labelRu':'Зеленокумск'},
     {'value':'Zernograd','labelRu':'Зерноград'},
     {'value':'Zeya','labelRu':'Зея'},
     {'value':'Winter','labelRu':'Зима'},
     {'value':'Chrysostom','labelRu':'Златоуст'},
     {'value':'Zlynka','labelRu':'Злынка'},
     {'value':'Zmeinogorsk','labelRu':'Змеиногорск'},
     {'value':'Znamensk','labelRu':'Знаменск'},
     {'value':'Tines','labelRu':'Зубцов'},
     {'value':'Zuevka','labelRu':'Зуевка'},
     {'value':'Ivangorod','labelRu':'Ивангород'},
     {'value':'Ivanovo','labelRu':'Иваново'},
     {'value':'Ivanteevka','labelRu':'Ивантеевка'},
     {'value':'Ivdel','labelRu':'Ивдель'},
     {'value':'Igarka','labelRu':'Игарка'},
     {'value':'Izhevsk','labelRu':'Ижевск'},
     {'value':'Izberbash','labelRu':'Избербаш'},
     {'value':'Abundant','labelRu':'Изобильный'},
     {'value':'Ilan','labelRu':'Иланский'},
     {'value':'Inza','labelRu':'Инза'},
     {'value':'Innopolis','labelRu':'Иннополис'},
     {'value':'Insar','labelRu':'Инсар'},
     {'value':'Inta','labelRu':'Инта'},
     {'value':'Yoshkar-Ola','labelRu':'Йошкар-Ола'},
     {'value':'Ipatovo','labelRu':'Ипатово'},
     {'value':'Irbit','labelRu':'Ирбит'},
     {'value':'Irkutsk','labelRu':'Иркутск'},
     {'value':'Isilkul','labelRu':'Исилькуль'},
     {'value':'Iskitim','labelRu':'Искитим'},
     {'value':'Istria','labelRu':'Истра'},
     {'value':'Ishim','labelRu':'Ишим'},
     {'value':'Ishimbay','labelRu':'Ишимбай'},
     {'value':'Kadnikov','labelRu':'Кадников'},
     {'value':'Kazan','labelRu':'Казань'},
     {'value':'Kalach','labelRu':'Калач'},
     {'value':'Kalachinsk','labelRu':'Калачинск'},
     {'value':'Kalach-on-Don','labelRu':'Калач-на-Дону'},
     {'value':'Kaliningrad','labelRu':'Калининград'},
     {'value':'Kalininsk','labelRu':'Калининск'},
     {'value':'Kaltan','labelRu':'Калтан'},
     {'value':'Kaluga','labelRu':'Калуга'},
     {'value':'Kalyazin','labelRu':'Калязин'},
     {'value':'Kambarka','labelRu':'Камбарка'},
     {'value':'Kamenka','labelRu':'Каменка'},
     {'value':'Kamennogorsk','labelRu':'Каменногорск'},
     {'value':'Kamensk-Uralsky','labelRu':'Каменск-Уральский'},
     {'value':'Kamensk-Shakhtinsky','labelRu':'Каменск-Шахтинский'},
     {'value':'Stone on ob','labelRu':'Камень-на-Оби'},
     {'value':'Kameshkovo','labelRu':'Камешково'},
     {'value':'Kamyzyak','labelRu':'Камызяк'},
     {'value':'Kamyshin','labelRu':'Камышин'},
     {'value':'Kamyshlov','labelRu':'Камышлов'},
     {'value':'Kanash','labelRu':'Канаш'},
     {'value':'Kandalaksha','labelRu':'Кандалакша'},
     {'value':'Kansk','labelRu':'Канск'},
     {'value':'Karabanovo','labelRu':'Карабаново'},
     {'value':'Karabash','labelRu':'Карабаш'},
     {'value':'Karabulak','labelRu':'Карабулак'},
     {'value':'Karasuk','labelRu':'Карасук'},
     {'value':'Karachaevsk','labelRu':'Карачаевск'},
     {'value':'Karachev','labelRu':'Карачев'},
     {'value':'Kargat','labelRu':'Каргат'},
     {'value':'Kargopol','labelRu':'Каргополь'},
     {'value':'Karpinsk','labelRu':'Карпинск'},
     {'value':'Kartaly','labelRu':'Карталы'},
     {'value':'Kasimov','labelRu':'Касимов'},
     {'value':'Casley','labelRu':'Касли'},
     {'value':'Kaspiysk','labelRu':'Каспийск'},
     {'value':'Katav-Ivanovsk','labelRu':'Катав-Ивановск'},
     {'value':'Kataysk','labelRu':'Катайск'},
     {'value':'Kachkanar','labelRu':'Качканар'},
     {'value':'Kashin','labelRu':'Кашин'},
     {'value':'Kashira','labelRu':'Кашира'},
     {'value':'Cedar','labelRu':'Кедровый'},
     {'value':'Kemerovo','labelRu':'Кемерово'},
     {'value':'Kem','labelRu':'Кемь'},
     {'value':'Kerch','labelRu':'Керчь'},
     {'value':'Kizel','labelRu':'Кизел'},
     {'value':'Kizilyurt','labelRu':'Кизилюрт'},
     {'value':'Kizlyar','labelRu':'Кизляр'},
     {'value':'Kimovsk','labelRu':'Кимовск'},
     {'value':'Kimry','labelRu':'Кимры'},
     {'value':'Kingisepp','labelRu':'Кингисепп'},
     {'value':'Kinel','labelRu':'Кинель'},
     {'value':'Kineshma','labelRu':'Кинешма'},
     {'value':'Kireevsk','labelRu':'Киреевск'},
     {'value':'Kirensk','labelRu':'Киренск'},
     {'value':'Kirzhach','labelRu':'Киржач'},
     {'value':'Kirillov','labelRu':'Кириллов'},
     {'value':'Kirishi','labelRu':'Кириши'},
     {'value':'Kirov','labelRu':'Киров'},
     {'value':'Kirov','labelRu':'Киров'},
     {'value':'Kirovgrad','labelRu':'Кировград'},
     {'value':'Kirovo-Chepetsk','labelRu':'Кирово-Чепецк'},
     {'value':'Kirovsk','labelRu':'Кировск'},
     {'value':'Kirovsk','labelRu':'Кировск'},
     {'value':'Kirs','labelRu':'Кирс'},
     {'value':'Kirsanov','labelRu':'Кирсанов'},
     {'value':'Kiselevsk','labelRu':'Киселёвск'},
     {'value':'Kislovodsk','labelRu':'Кисловодск'},
     {'value':'Wedge','labelRu':'Клин'},
     {'value':'Klintsy','labelRu':'Клинцы'},
     {'value':'Knyaginino','labelRu':'Княгинино'},
     {'value':'Kovdor','labelRu':'Ковдор'},
     {'value':'Carpet','labelRu':'Ковров'},
     {'value':'Kovylkino','labelRu':'Ковылкино'},
     {'value':'Kogalym','labelRu':'Когалым'},
     {'value':'Kodinsk','labelRu':'Кодинск'},
     {'value':'Kozelsk','labelRu':'Козельск'},
     {'value':'Kozlovka','labelRu':'Козловка'},
     {'value':'Kozmodemyansk','labelRu':'Козьмодемьянск'},
     {'value':'Cola','labelRu':'Кола'},
     {'value':'Kologriv','labelRu':'Кологрив'},
     {'value':'Kolomna','labelRu':'Коломна'},
     {'value':'Kolpashevo','labelRu':'Колпашево'},
     {'value':'Kolchugino','labelRu':'Кольчугино'},
     {'value':'Communard','labelRu':'Коммунар'},
     {'value':'Komsomolsk','labelRu':'Комсомольск'},
     {'value':'Komsomolsk-on-Amur','labelRu':'Комсомольск-на-Амуре'},
     {'value':'Konakovo','labelRu':'Конаково'},
     {'value':'Kondopoga','labelRu':'Кондопога'},
     {'value':'Kondrovo','labelRu':'Кондрово'},
     {'value':'Konstantinovsk','labelRu':'Константиновск'},
     {'value':'Kopeisk','labelRu':'Копейск'},
     {'value':'Shiplino','labelRu':'Кораблино'},
     {'value':'Korenovsk','labelRu':'Кореновск'},
     {'value':'Korkino','labelRu':'Коркино'},
     {'value':'Korolev','labelRu':'Королёв'},
     {'value':'Short','labelRu':'Короча'},
     {'value':'Korsakov','labelRu':'Корсаков'},
     {'value':'Koryazhma','labelRu':'Коряжма'},
     {'value':'Costerevo','labelRu':'Костерёво'},
     {'value':'Kostomuksha','labelRu':'Костомукша'},
     {'value':'Kostroma','labelRu':'Кострома'},
     {'value':'Kotelniki','labelRu':'Котельники'},
     {'value':'Kotelnikovo','labelRu':'Котельниково'},
     {'value':'Kotelnich','labelRu':'Котельнич'},
     {'value':'Kotlas','labelRu':'Котлас'},
     {'value':'Kotovo','labelRu':'Котово'},
     {'value':'Kotovsk','labelRu':'Котовск'},
     {'value':'Kokhma','labelRu':'Кохма'},
     {'value':'Krasavino','labelRu':'Красавино'},
     {'value':'Krasnoarmeysk','labelRu':'Красноармейск'},
     {'value':'Krasnoarmeysk','labelRu':'Красноармейск'},
     {'value':'Krasnovishersk','labelRu':'Красновишерск'},
     {'value':'Krasnogorsk','labelRu':'Красногорск'},
     {'value':'Krasnodar','labelRu':'Краснодар'},
     {'value':'Krasnozavodsk','labelRu':'Краснозаводск'},
     {'value':'Krasnoznamensk','labelRu':'Краснознаменск'},
     {'value':'Krasnoznamensk','labelRu':'Краснознаменск'},
     {'value':'Krasnokamensk','labelRu':'Краснокаменск'},
     {'value':'Krasnokamsk','labelRu':'Краснокамск'},
     {'value':'Krasnoperekopsk','labelRu':'Красноперекопск'},
     {'value':'Krasnoslobodsk','labelRu':'Краснослободск'},
     {'value':'Krasnoslobodsk','labelRu':'Краснослободск'},
     {'value':'Krasnoturyinsk','labelRu':'Краснотурьинск'},
     {'value':'Krasnouralsk','labelRu':'Красноуральск'},
     {'value':'Krasnoufimsk','labelRu':'Красноуфимск'},
     {'value':'Krasnoyarsk','labelRu':'Красноярск'},
     {'value':'Red Kut','labelRu':'Красный Кут'},
     {'value':'Red Sulin','labelRu':'Красный Сулин'},
     {'value':'Red Hill','labelRu':'Красный Холм'},
     {'value':'Kremienki','labelRu':'Кремёнки'},
     {'value':'Kropotkin','labelRu':'Кропоткин'},
     {'value':'Krymsk','labelRu':'Крымск'},
     {'value':'Kstovo','labelRu':'Кстово'},
     {'value':'Cuban','labelRu':'Кубинка'},
     {'value':'Kuvandyk','labelRu':'Кувандык'},
     {'value':'Kuvshinovo','labelRu':'Кувшиново'},
     {'value':'Kudymkar','labelRu':'Кудымкар'},
     {'value':'Kuznetsk','labelRu':'Кузнецк'},
     {'value':'Kuibyshev','labelRu':'Куйбышев'},
     {'value':'Cookmore','labelRu':'Кукмор'},
     {'value':'Kulebaki','labelRu':'Кулебаки'},
     {'value':'Kumertau','labelRu':'Кумертау'},
     {'value':'Kungur','labelRu':'Кунгур'},
     {'value':'Kupino','labelRu':'Купино'},
     {'value':'Mound','labelRu':'Курган'},
     {'value':'Kurganinsk','labelRu':'Курганинск'},
     {'value':'Kurilsk','labelRu':'Курильск'},
     {'value':'Kurlovo','labelRu':'Курлово'},
     {'value':'Kurovskoye','labelRu':'Куровское'},
     {'value':'Kursk','labelRu':'Курск'},
     {'value':'Kurtamysh','labelRu':'Куртамыш'},
     {'value':'Kurchatov','labelRu':'Курчатов'},
     {'value':'Kusa','labelRu':'Куса'},
     {'value':'Kushva','labelRu':'Кушва'},
     {'value':'Kyzyl','labelRu':'Кызыл'},
     {'value':'Kyshtym','labelRu':'Кыштым'},
     {'value':'Kyahta','labelRu':'Кяхта'},
     {'value':'Labinsk','labelRu':'Лабинск'},
     {'value':'Labytnangi','labelRu':'Лабытнанги'},
     {'value':'Lagan','labelRu':'Лагань'},
     {'value':'Ladushkin','labelRu':'Ладушкин'},
     {'value':'Laishevo','labelRu':'Лаишево'},
     {'value':'Lakinsk','labelRu':'Лакинск'},
     {'value':'Langepas','labelRu':'Лангепас'},
     {'value':'Lahdenpohja','labelRu':'Лахденпохья'},
     {'value':'Lebedyan','labelRu':'Лебедянь'},
     {'value':'Leninogorsk','labelRu':'Лениногорск'},
     {'value':'Leninsk','labelRu':'Ленинск'},
     {'value':'Leninsk-Kuznetsky','labelRu':'Ленинск-Кузнецкий'},
     {'value':'Lensk','labelRu':'Ленск'},
     {'value':'Lermontov','labelRu':'Лермонтов'},
     {'value':'Forest','labelRu':'Лесной'},
     {'value':'Lesozavodsk','labelRu':'Лесозаводск'},
     {'value':'Lesosibirsk','labelRu':'Лесосибирск'},
     {'value':'Livny','labelRu':'Ливны'},
     {'value':'Likino-Dulyovo','labelRu':'Ликино-Дулёво'},
     {'value':'Lipetsk','labelRu':'Липецк'},
     {'value':'Limes','labelRu':'Липки'},
     {'value':'Liski','labelRu':'Лиски'},
     {'value':'Likhoslavl','labelRu':'Лихославль'},
     {'value':'Lobnya','labelRu':'Лобня'},
     {'value':'Lodeynoye Pole','labelRu':'Лодейное Поле'},
     {'value':'Losino-Petrovsky','labelRu':'Лосино-Петровский'},
     {'value':'Meadows','labelRu':'Луга'},
     {'value':'Pocket','labelRu':'Луза'},
     {'value':'Lukoyanov','labelRu':'Лукоянов'},
     {'value':'Lukhovitsy','labelRu':'Луховицы'},
     {'value':'Lyskovo','labelRu':'Лысково'},
     {'value':'Lysva','labelRu':'Лысьва'},
     {'value':'Lytkarino','labelRu':'Лыткарино'},
     {'value':'Lgov','labelRu':'Льгов'},
     {'value':'Lyuban','labelRu':'Любань'},
     {'value':'Lyubertsy','labelRu':'Люберцы'},
     {'value':'Love','labelRu':'Любим'},
     {'value':'Lyudinovo','labelRu':'Людиново'},
     {'value':'Lyantor','labelRu':'Лянтор'},
     {'value':'Magadan','labelRu':'Магадан'},
     {'value':'Magas','labelRu':'Магас'},
     {'value':'Magnitogorsk','labelRu':'Магнитогорск'},
     {'value':'Maykop','labelRu':'Майкоп'},
     {'value':'May','labelRu':'Майский'},
     {'value':'Makarov','labelRu':'Макаров'},
     {'value':'Makaryev','labelRu':'Макарьев'},
     {'value':'Makushino','labelRu':'Макушино'},
     {'value':'Malaya Vishera','labelRu':'Малая Вишера'},
     {'value':'Malgobek','labelRu':'Малгобек'},
     {'value':'Malmyzh','labelRu':'Малмыж'},
     {'value':'Maloarkhangelsk','labelRu':'Малоархангельск'},
     {'value':'Maloyaroslavets','labelRu':'Малоярославец'},
     {'value':'Mamadysh','labelRu':'Мамадыш'},
     {'value':'Mamonovo','labelRu':'Мамоново'},
     {'value':'Manturovo','labelRu':'Мантурово'},
     {'value':'Mariinsk','labelRu':'Мариинск'},
     {'value':'Mariinsky Posad','labelRu':'Мариинский Посад'},
     {'value':'Marx','labelRu':'Маркс'},
     {'value':'Makhachkala','labelRu':'Махачкала'},
     {'value':'Mglin','labelRu':'Мглин'},
     {'value':'Megion','labelRu':'Мегион'},
     {'value':'Medvezhiegorsk','labelRu':'Медвежьегорск'},
     {'value':'Mednogorsk','labelRu':'Медногорск'},
     {'value':'Medyn','labelRu':'Медынь'},
     {'value':'Mizhhiria','labelRu':'Межгорье'},
     {'value':'Mezhdurechensk','labelRu':'Междуреченск'},
     {'value':'Mezen','labelRu':'Мезень'},
     {'value':'Melenki','labelRu':'Меленки'},
     {'value':'Meleuz','labelRu':'Мелеуз'},
     {'value':'Mendeleevsk','labelRu':'Менделеевск'},
     {'value':'Menzelinsk','labelRu':'Мензелинск'},
     {'value':'Meshchovsk','labelRu':'Мещовск'},
     {'value':'Miass','labelRu':'Миасс'},
     {'value':'Mikun','labelRu':'Микунь'},
     {'value':'Millerovo','labelRu':'Миллерово'},
     {'value':'Mineral water','labelRu':'Минеральные Воды'},
     {'value':'Minusinsk','labelRu':'Минусинск'},
     {'value':'Minyar','labelRu':'Миньяр'},
     {'value':'Peaceful','labelRu':'Мирный'},
     {'value':'Peaceful','labelRu':'Мирный'},
     {'value':'Mikhailov','labelRu':'Михайлов'},
     {'value':'Mikhaylovka','labelRu':'Михайловка'},
     {'value':'Mikhaylovsk','labelRu':'Михайловск'},
     {'value':'Mikhaylovsk','labelRu':'Михайловск'},
     {'value':'Michurinsk','labelRu':'Мичуринск'},
     {'value':'Mogocha','labelRu':'Могоча'},
     {'value':'Mozhaisk','labelRu':'Можайск'},
     {'value':'Mozhga','labelRu':'Можга'},
     {'value':'Mozdok','labelRu':'Моздок'},
     {'value':'Monchegorsk','labelRu':'Мончегорск'},
     {'value':'Morozovsk','labelRu':'Морозовск'},
     {'value':'Morshansk','labelRu':'Моршанск'},
     {'value':'Mosalsk','labelRu':'Мосальск'},
     {'value':'Moscow','labelRu':'Москва'},
     {'value':'Muravlenko','labelRu':'Муравленко'},
     {'value':'Murashi','labelRu':'Мураши'},
     {'value':'Murmansk','labelRu':'Мурманск'},
     {'value':'Moore','labelRu':'Муром'},
     {'value':'Mtsensk','labelRu':'Мценск'},
     {'value':'Myski','labelRu':'Мыски'},
     {'value':'Mytishchi','labelRu':'Мытищи'},
     {'value':'Myshkin','labelRu':'Мышкин'},
     {'value':'Naberezhnye Chelny','labelRu':'Набережные Челны'},
     {'value':'Navashino','labelRu':'Навашино'},
     {'value':'Navoloki','labelRu':'Наволоки'},
     {'value':'Nadym','labelRu':'Надым'},
     {'value':'Nazarovo','labelRu':'Назарово'},
     {'value':'Nazran','labelRu':'Назрань'},
     {'value':'Nazyvaevsk','labelRu':'Называевск'},
     {'value':'Nalchik','labelRu':'Нальчик'},
     {'value':'Narimanov','labelRu':'Нариманов'},
     {'value':'Naro-Fominsk','labelRu':'Наро-Фоминск'},
     {'value':'Nartkala','labelRu':'Нарткала'},
     {'value':'Naryan-Mar','labelRu':'Нарьян-Мар'},
     {'value':'Find','labelRu':'Находка'},
     {'value':'Nevel','labelRu':'Невель'},
     {'value':'Nevelsk','labelRu':'Невельск'},
     {'value':'Nevinnomyssk','labelRu':'Невинномысск'},
     {'value':'Nevyansk','labelRu':'Невьянск'},
     {'value':'Nelidovo','labelRu':'Нелидово'},
     {'value':'Neman','labelRu':'Неман'},
     {'value':'Nerekhta','labelRu':'Нерехта'},
     {'value':'Nerchinsk','labelRu':'Нерчинск'},
     {'value':'Neryungri','labelRu':'Нерюнгри'},
     {'value':'Nesterov','labelRu':'Нестеров'},
     {'value':'Neftegorsk','labelRu':'Нефтегорск'},
     {'value':'Neftekamsk','labelRu':'Нефтекамск'},
     {'value':'Neftekumsk','labelRu':'Нефтекумск'},
     {'value':'Nefteyugansk','labelRu':'Нефтеюганск'},
     {'value':'Not me','labelRu':'Нея'},
     {'value':'Nizhnevartovsk','labelRu':'Нижневартовск'},
     {'value':'Nizhnekamsk','labelRu':'Нижнекамск'},
     {'value':'Nizhneudinsk','labelRu':'Нижнеудинск'},
     {'value':'Lower Sergi','labelRu':'Нижние Серги'},
     {'value':'Nizhny Lomov','labelRu':'Нижний Ломов'},
     {'value':'Nizhny Novgorod','labelRu':'Нижний Новгород'},
     {'value':'Nizhny Tagil','labelRu':'Нижний Тагил'},
     {'value':'Lower Salda','labelRu':'Нижняя Салда'},
     {'value':'Lower Tour','labelRu':'Нижняя Тура'},
     {'value':'Nikolaevsk','labelRu':'Николаевск'},
     {'value':'Nikolaevsk-on-Amur','labelRu':'Николаевск-на-Амуре'},
     {'value':'Nikolsk','labelRu':'Никольск'},
     {'value':'Nikolsk','labelRu':'Никольск'},
     {'value':'Nikolskoe','labelRu':'Никольское'},
     {'value':'New Ladoga','labelRu':'Новая Ладога'},
     {'value':'New Lyalya','labelRu':'Новая Ляля'},
     {'value':'Novoaleksandrovsk','labelRu':'Новоалександровск'},
     {'value':'Novoaltaisk','labelRu':'Новоалтайск'},
     {'value':'Novoanninsky','labelRu':'Новоаннинский'},
     {'value':'Novovoronezh','labelRu':'Нововоронеж'},
     {'value':'Novodvinsk','labelRu':'Новодвинск'},
     {'value':'Novozybkov','labelRu':'Новозыбков'},
     {'value':'Novokubansk','labelRu':'Новокубанск'},
     {'value':'Novokuznetsk','labelRu':'Новокузнецк'},
     {'value':'Novokuibyshevsk','labelRu':'Новокуйбышевск'},
     {'value':'Novomichurinsk','labelRu':'Новомичуринск'},
     {'value':'Novomoskovsk','labelRu':'Новомосковск'},
     {'value':'Novopavlovsk','labelRu':'Новопавловск'},
     {'value':'Novorzhev','labelRu':'Новоржев'},
     {'value':'Novorossiysk','labelRu':'Новороссийск'},
     {'value':'Novosibirsk','labelRu':'Новосибирск'},
     {'value':'Novosil','labelRu':'Новосиль'},
     {'value':'Novosokolniki','labelRu':'Новосокольники'},
     {'value':'Novotroitsk','labelRu':'Новотроицк'},
     {'value':'Novouzensk','labelRu':'Новоузенск'},
     {'value':'Novoulyanovsk','labelRu':'Новоульяновск'},
     {'value':'Novouralsk','labelRu':'Новоуральск'},
     {'value':'Novokhopyorsk','labelRu':'Новохопёрск'},
     {'value':'Novocheboksarsk','labelRu':'Новочебоксарск'},
     {'value':'Novocherkassk','labelRu':'Новочеркасск'},
     {'value':'Novoshakhtinsk','labelRu':'Новошахтинск'},
     {'value':'New Oskol','labelRu':'Новый Оскол'},
     {'value':'New Urengoy','labelRu':'Новый Уренгой'},
     {'value':'Noginsk','labelRu':'Ногинск'},
     {'value':'Nolinsk','labelRu':'Нолинск'},
     {'value':'Norilsk','labelRu':'Норильск'},
     {'value':'Noyabrsk','labelRu':'Ноябрьск'},
     {'value':'Nurlat','labelRu':'Нурлат'},
     {'value':'Nytva','labelRu':'Нытва'},
     {'value':'Nyurba','labelRu':'Нюрба'},
     {'value':'Nyagan','labelRu':'Нягань'},
     {'value':'Nyazepetrovsk','labelRu':'Нязепетровск'},
     {'value':'Nyandoma','labelRu':'Няндома'},
     {'value':'Irradiation','labelRu':'Облучье'},
     {'value':'Obninsk','labelRu':'Обнинск'},
     {'value':'Oboyan','labelRu':'Обоянь'},
     {'value':'Ob','labelRu':'Обь'},
     {'value':'Odintsovo','labelRu':'Одинцово'},
     {'value':'Ozersk','labelRu':'Озёрск'},
     {'value':'Ozersk','labelRu':'Озёрск'},
     {'value':'Lakes','labelRu':'Озёры'},
     {'value':'Oktyabrsk','labelRu':'Октябрьск'},
     {'value':'October','labelRu':'Октябрьский'},
     {'value':'Okulovka','labelRu':'Окуловка'},
     {'value':'Olekminsk','labelRu':'Олёкминск'},
     {'value':'Olenegorsk','labelRu':'Оленегорск'},
     {'value':'Olonets','labelRu':'Олонец'},
     {'value':'Omsk','labelRu':'Омск'},
     {'value':'Omutninsk','labelRu':'Омутнинск'},
     {'value':'Onega','labelRu':'Онега'},
     {'value':'Opochka','labelRu':'Опочка'},
     {'value':'Eagle','labelRu':'Орёл'},
     {'value':'Orenburg','labelRu':'Оренбург'},
     {'value':'Orekhovo-Zuyevo','labelRu':'Орехово-Зуево'},
     {'value':'Eagles','labelRu':'Орлов'},
     {'value':'Orsk','labelRu':'Орск'},
     {'value':'Wasp','labelRu':'Оса'},
     {'value':'Osinniki','labelRu':'Осинники'},
     {'value':'Ostashkov','labelRu':'Осташков'},
     {'value':'Isle','labelRu':'Остров'},
     {'value':'Island','labelRu':'Островной'},
     {'value':'Ostrogozhsk','labelRu':'Острогожск'},
     {'value':'Gratifying','labelRu':'Отрадное'},
     {'value':'Gratifying','labelRu':'Отрадный'},
     {'value':'Okha','labelRu':'Оха'},
     {'value':'Okhansk','labelRu':'Оханск'},
     {'value':'Ocher','labelRu':'Очёр'},
     {'value':'Pavlovo','labelRu':'Павлово'},
     {'value':'Pavlovsk','labelRu':'Павловск'},
     {'value':'Pavlovsky Posad','labelRu':'Павловский Посад'},
     {'value':'Pallasovka','labelRu':'Палласовка'},
     {'value':'Partizansk','labelRu':'Партизанск'},
     {'value':'Pevek','labelRu':'Певек'},
     {'value':'Penza','labelRu':'Пенза'},
     {'value':'Pervomaisk','labelRu':'Первомайск'},
     {'value':'Pervouralsk','labelRu':'Первоуральск'},
     {'value':'Transportation','labelRu':'Перевоз'},
     {'value':'Relight','labelRu':'Пересвет'},
     {'value':'Pereslavl-Zalessky','labelRu':'Переславль-Залесский'},
     {'value':'Permian','labelRu':'Пермь'},
     {'value':'Pestovo','labelRu':'Пестово'},
     {'value':'Petrov Val','labelRu':'Петров Вал'},
     {'value':'Petrovsk','labelRu':'Петровск'},
     {'value':'Petrovsk-Zabaykalsky','labelRu':'Петровск-Забайкальский'},
     {'value':'Petrozavodsk','labelRu':'Петрозаводск'},
     {'value':'Petropavlovsk-Kamchatsky','labelRu':'Петропавловск-Камчатский'},
     {'value':'Petukhovo','labelRu':'Петухово'},
     {'value':'Cockerels','labelRu':'Петушки'},
     {'value':'Pechora','labelRu':'Печора'},
     {'value':'Pechora','labelRu':'Печоры'},
     {'value':'Pikalyovo','labelRu':'Пикалёво'},
     {'value':'Pioneer','labelRu':'Пионерский'},
     {'value':'Pitkäranta','labelRu':'Питкяранта'},
     {'value':'Plavsk','labelRu':'Плавск'},
     {'value':'Plast','labelRu':'Пласт'},
     {'value':'Ples','labelRu':'Плёс'},
     {'value':'Povorino','labelRu':'Поворино'},
     {'value':'Podolsk','labelRu':'Подольск'},
     {'value':'Podporozhye','labelRu':'Подпорожье'},
     {'value':'Pokachi','labelRu':'Покачи'},
     {'value':'Cover','labelRu':'Покров'},
     {'value':'Pokrovsk','labelRu':'Покровск'},
     {'value':'Polevskoy','labelRu':'Полевской'},
     {'value':'Polessk','labelRu':'Полесск'},
     {'value':'Polysaevo','labelRu':'Полысаево'},
     {'value':'Polar dawns','labelRu':'Полярные Зори'},
     {'value':'Polar','labelRu':'Полярный'},
     {'value':'Poronaysk','labelRu':'Поронайск'},
     {'value':'Porkhov','labelRu':'Порхов'},
     {'value':'Pohvistnevo','labelRu':'Похвистнево'},
     {'value':'Pochep','labelRu':'Почеп'},
     {'value':'Mending','labelRu':'Починок'},
     {'value':'Poshekhonye','labelRu':'Пошехонье'},
     {'value':'Pravdinsk','labelRu':'Правдинск'},
     {'value':'Privolzhsk','labelRu':'Приволжск'},
     {'value':'Primorsk','labelRu':'Приморск'},
     {'value':'Primorsk','labelRu':'Приморск'},
     {'value':'Primorsko-Akhtarsk','labelRu':'Приморско-Ахтарск'},
     {'value':'Priozersk','labelRu':'Приозерск'},
     {'value':'Prokopyevsk','labelRu':'Прокопьевск'},
     {'value':'Proletarsk','labelRu':'Пролетарск'},
     {'value':'Protvino','labelRu':'Протвино'},
     {'value':'Chill','labelRu':'Прохладный'},
     {'value':'Pskov','labelRu':'Псков'},
     {'value':'Pugachev','labelRu':'Пугачёв'},
     {'value':'Pudozh','labelRu':'Пудож'},
     {'value':'Pustoshka','labelRu':'Пустошка'},
     {'value':'Puchezh','labelRu':'Пучеж'},
     {'value':'Pushkino','labelRu':'Пушкино'},
     {'value':'Pushchino','labelRu':'Пущино'},
     {'value':'Pytalovo','labelRu':'Пыталово'},
     {'value':'Pyt-Yah','labelRu':'Пыть-Ях'},
     {'value':'Pyatigorsk','labelRu':'Пятигорск'},
     {'value':'Rainbow','labelRu':'Радужный'},
     {'value':'Rainbow','labelRu':'Радужный'},
     {'value':'Raychikhinsk','labelRu':'Райчихинск'},
     {'value':'Ramenskoye','labelRu':'Раменское'},
     {'value':'Rasskazovo','labelRu':'Рассказово'},
     {'value':'Revda','labelRu':'Ревда'},
     {'value':'Dir','labelRu':'Реж'},
     {'value':'Reutov','labelRu':'Реутов'},
     {'value':'Rzhev','labelRu':'Ржев'},
     {'value':'Springs','labelRu':'Родники'},
     {'value':'Roslavl','labelRu':'Рославль'},
     {'value':'Rossosh','labelRu':'Россошь'},
     {'value':'Rostov','labelRu':'Ростов'},
     {'value':'Rostov-on-Don','labelRu':'Ростов-на-Дону'},
     {'value':'Roshal','labelRu':'Рошаль'},
     {'value':'Rtishchevo','labelRu':'Ртищево'},
     {'value':'Rubtsovsk','labelRu':'Рубцовск'},
     {'value':'Rudnya','labelRu':'Рудня'},
     {'value':'Ruza','labelRu':'Руза'},
     {'value':'Ruzayevka','labelRu':'Рузаевка'},
     {'value':'Rybinsk','labelRu':'Рыбинск'},
     {'value':'Fish','labelRu':'Рыбное'},
     {'value':'Rylsk','labelRu':'Рыльск'},
     {'value':'Ryazhsk','labelRu':'Ряжск'},
     {'value':'Ryazan','labelRu':'Рязань'},
     {'value':'Saki','labelRu':'Саки'},
     {'value':'Salavat','labelRu':'Салават'},
     {'value':'Salair','labelRu':'Салаир'},
     {'value':'Salekhard','labelRu':'Салехард'},
     {'value':'Salsk','labelRu':'Сальск'},
     {'value':'Samara','labelRu':'Самара'},
     {'value':'St. Petersburg','labelRu':'Санкт-Петербург'},
     {'value':'Saransk','labelRu':'Саранск'},
     {'value':'Sarapul','labelRu':'Сарапул'},
     {'value':'Saratov','labelRu':'Саратов'},
     {'value':'Sarov','labelRu':'Саров'},
     {'value':'Sasovo','labelRu':'Сасово'},
     {'value':'Satka','labelRu':'Сатка'},
     {'value':'Safonovo','labelRu':'Сафоново'},
     {'value':'Sayanogorsk','labelRu':'Саяногорск'},
     {'value':'Sayansk','labelRu':'Саянск'},
     {'value':'Svetlogorsk','labelRu':'Светлогорск'},
     {'value':'Svetlograd','labelRu':'Светлоград'},
     {'value':'Light coloured','labelRu':'Светлый'},
     {'value':'Svetogorsk','labelRu':'Светогорск'},
     {'value':'Svirsk','labelRu':'Свирск'},
     {'value':'Free','labelRu':'Свободный'},
     {'value':'Sebezh','labelRu':'Себеж'},
     {'value':'Sevastopol','labelRu':'Севастополь'},
     {'value':'Severobaykalsk','labelRu':'Северобайкальск'},
     {'value':'Severodvinsk','labelRu':'Северодвинск'},
     {'value':'Severo-Kurilsk','labelRu':'Северо-Курильск'},
     {'value':'Severomorsk','labelRu':'Североморск'},
     {'value':'Severouralsk','labelRu':'Североуральск'},
     {'value':'Seversk','labelRu':'Северск'},
     {'value':'Sevsk','labelRu':'Севск'},
     {'value':'Segezha','labelRu':'Сегежа'},
     {'value':'Village','labelRu':'Сельцо'},
     {'value':'Semyonov','labelRu':'Семёнов'},
     {'value':'Semikarakorsk','labelRu':'Семикаракорск'},
     {'value':'Semiluki','labelRu':'Семилуки'},
     {'value':'Sengiley','labelRu':'Сенгилей'},
     {'value':'Serafimovich','labelRu':'Серафимович'},
     {'value':'Sergach','labelRu':'Сергач'},
     {'value':'Sergiev Posad','labelRu':'Сергиев Посад'},
     {'value':'Serdobsk','labelRu':'Сердобск'},
     {'value':'Serov','labelRu':'Серов'},
     {'value':'Serpukhov','labelRu':'Серпухов'},
     {'value':'Sertolovo','labelRu':'Сертолово'},
     {'value':'Sibay','labelRu':'Сибай'},
     {'value':'Sim','labelRu':'Сим'},
     {'value':'Simferopol','labelRu':'Симферополь'},
     {'value':'Skovorodino','labelRu':'Сковородино'},
     {'value':'Skopin','labelRu':'Скопин'},
     {'value':'Slavgorod','labelRu':'Славгород'},
     {'value':'Slavsk','labelRu':'Славск'},
     {'value':'Slavyansk-on-Kuban','labelRu':'Славянск-на-Кубани'},
     {'value':'Slates','labelRu':'Сланцы'},
     {'value':'Slobodskoy','labelRu':'Слободской'},
     {'value':'Slyudyanka','labelRu':'Слюдянка'},
     {'value':'Smolensk','labelRu':'Смоленск'},
     {'value':'Snezhinsk','labelRu':'Снежинск'},
     {'value':'Snezhnogorsk','labelRu':'Снежногорск'},
     {'value':'Sobinka','labelRu':'Собинка'},
     {'value':'Sovetsk','labelRu':'Советск'},
     {'value':'Sovetsk','labelRu':'Советск'},
     {'value':'Sovetsk','labelRu':'Советск'},
     {'value':'Sovetskaya Gavan','labelRu':'Советская Гавань'},
     {'value':'Soviet','labelRu':'Советский'},
     {'value':'Falcon','labelRu':'Сокол'},
     {'value':'Soligalich','labelRu':'Солигалич'},
     {'value':'Solikamsk','labelRu':'Соликамск'},
     {'value':'Solnechnogorsk','labelRu':'Солнечногорск'},
     {'value':'Solvychegodsk','labelRu':'Сольвычегодск'},
     {'value':'Sol-Iletsk','labelRu':'Соль-Илецк'},
     {'value':'Soltsy','labelRu':'Сольцы'},
     {'value':'Sorochinsk','labelRu':'Сорочинск'},
     {'value':'Sorsk','labelRu':'Сорск'},
     {'value':'Sortavala','labelRu':'Сортавала'},
     {'value':'Sosensky','labelRu':'Сосенский'},
     {'value':'Sosnovka','labelRu':'Сосновка'},
     {'value':'Sosnovoborsk','labelRu':'Сосновоборск'},
     {'value':'Pinery','labelRu':'Сосновый Бор'},
     {'value':'Sosnogorsk','labelRu':'Сосногорск'},
     {'value':'Sochi','labelRu':'Сочи'},
     {'value':'Spas-Demensk','labelRu':'Спас-Деменск'},
     {'value':'Spas-Klepiki','labelRu':'Спас-Клепики'},
     {'value':'Spassk','labelRu':'Спасск'},
     {'value':'Spassk-Dalny','labelRu':'Спасск-Дальний'},
     {'value':'Spassk-Ryazan','labelRu':'Спасск-Рязанский'},
     {'value':'Srednekolymsk','labelRu':'Среднеколымск'},
     {'value':'Sredneuralsk','labelRu':'Среднеуральск'},
     {'value':'Sretensk','labelRu':'Сретенск'},
     {'value':'Stavropol','labelRu':'Ставрополь'},
     {'value':'Old Kupavna','labelRu':'Старая Купавна'},
     {'value':'Staraya Russa','labelRu':'Старая Русса'},
     {'value':'Staritsa','labelRu':'Старица'},
     {'value':'Starodub','labelRu':'Стародуб'},
     {'value':'Old Crimea','labelRu':'Старый Крым'},
     {'value':'Stary Oskol','labelRu':'Старый Оскол'},
     {'value':'Sterlitamak','labelRu':'Стерлитамак'},
     {'value':'Strezhevoy','labelRu':'Стрежевой'},
     {'value':'Builder','labelRu':'Строитель'},
     {'value':'Strunino','labelRu':'Струнино'},
     {'value':'Stupino','labelRu':'Ступино'},
     {'value':'Suvorov','labelRu':'Суворов'},
     {'value':'Zander','labelRu':'Судак'},
     {'value':'Sudja','labelRu':'Суджа'},
     {'value':'Sudogda','labelRu':'Судогда'},
     {'value':'Suzdal','labelRu':'Суздаль'},
     {'value':'Sunzha','labelRu':'Сунжа'},
     {'value':'Suoyarvi','labelRu':'Суоярви'},
     {'value':'Suraj','labelRu':'Сураж'},
     {'value':'Surgut','labelRu':'Сургут'},
     {'value':'Surovikino','labelRu':'Суровикино'},
     {'value':'Sursk','labelRu':'Сурск'},
     {'value':'Susuman','labelRu':'Сусуман'},
     {'value':'Sukhinichi','labelRu':'Сухиничи'},
     {'value':'Dry log','labelRu':'Сухой Лог'},
     {'value':'Sizran','labelRu':'Сызрань'},
     {'value':'Syktyvkar','labelRu':'Сыктывкар'},
     {'value':'Sysert','labelRu':'Сысерть'},
     {'value':'Sychevka','labelRu':'Сычёвка'},
     {'value':'Syasstroy','labelRu':'Сясьстрой'},
     {'value':'Tavda','labelRu':'Тавда'},
     {'value':'Taganrog','labelRu':'Таганрог'},
     {'value':'Taiga','labelRu':'Тайга'},
     {'value':'Tayshet','labelRu':'Тайшет'},
     {'value':'Taldom','labelRu':'Талдом'},
     {'value':'Talitsa','labelRu':'Талица'},
     {'value':'Tambov','labelRu':'Тамбов'},
     {'value':'Tara','labelRu':'Тара'},
     {'value':'Tarko-Sale','labelRu':'Тарко-Сале'},
     {'value':'Tarusa','labelRu':'Таруса'},
     {'value':'Tatarsk','labelRu':'Татарск'},
     {'value':'Tashtagol','labelRu':'Таштагол'},
     {'value':'Tver','labelRu':'Тверь'},
     {'value':'Teberda','labelRu':'Теберда'},
     {'value':'Teikovo','labelRu':'Тейково'},
     {'value':'Temnikov','labelRu':'Темников'},
     {'value':'Temryuk','labelRu':'Темрюк'},
     {'value':'Terek','labelRu':'Терек'},
     {'value':'Aunty','labelRu':'Тетюши'},
     {'value':'Timashevsk','labelRu':'Тимашёвск'},
     {'value':'Tikhvin','labelRu':'Тихвин'},
     {'value':'Tikhoretsk','labelRu':'Тихорецк'},
     {'value':'Tobolsk','labelRu':'Тобольск'},
     {'value':'Toguchin','labelRu':'Тогучин'},
     {'value':'Tolyatti','labelRu':'Тольятти'},
     {'value':'Tomari','labelRu':'Томари'},
     {'value':'Tommot','labelRu':'Томмот'},
     {'value':'Tomsk','labelRu':'Томск'},
     {'value':'Fireboxes','labelRu':'Топки'},
     {'value':'Torzhok','labelRu':'Торжок'},
     {'value':'Toropets','labelRu':'Торопец'},
     {'value':'Tosno','labelRu':'Тосно'},
     {'value':'Totma','labelRu':'Тотьма'},
     {'value':'Trigorny','labelRu':'Трёхгорный'},
     {'value':'Troitsk','labelRu':'Троицк'},
     {'value':'Trubchevsk','labelRu':'Трубчевск'},
     {'value':'Tuapse','labelRu':'Туапсе'},
     {'value':'Tuymazy','labelRu':'Туймазы'},
     {'value':'Tula','labelRu':'Тула'},
     {'value':'Tulun','labelRu':'Тулун'},
     {'value':'Turan','labelRu':'Туран'},
     {'value':'Turinsk','labelRu':'Туринск'},
     {'value':'Tutaev','labelRu':'Тутаев'},
     {'value':'Tynda','labelRu':'Тында'},
     {'value':'Tyrnyauz','labelRu':'Тырныауз'},
     {'value':'Tyukalinsk','labelRu':'Тюкалинск'},
     {'value':'Tyumen','labelRu':'Тюмень'},
     {'value':'Uvarovo','labelRu':'Уварово'},
     {'value':'Uglegorsk','labelRu':'Углегорск'},
     {'value':'Uglich','labelRu':'Углич'},
     {'value':'Successful','labelRu':'Удачный'},
     {'value':'Udomlya','labelRu':'Удомля'},
     {'value':'Uzhur','labelRu':'Ужур'},
     {'value':'Nodular','labelRu':'Узловая'},
     {'value':'Ulan-Ude','labelRu':'Улан-Удэ'},
     {'value':'Ulyanovsk','labelRu':'Ульяновск'},
     {'value':'Unecha','labelRu':'Унеча'},
     {'value':'Uray','labelRu':'Урай'},
     {'value':'Uren','labelRu':'Урень'},
     {'value':'Urzhum','labelRu':'Уржум'},
     {'value':'Urus-Martan','labelRu':'Урус-Мартан'},
     {'value':'Uryupinsk','labelRu':'Урюпинск'},
     {'value':'Usinsk','labelRu':'Усинск'},
     {'value':'Usman','labelRu':'Усмань'},
     {'value':'Usolie','labelRu':'Усолье'},
     {'value':'Usolye-Siberian','labelRu':'Усолье-Сибирское'},
     {'value':'Ussuriisk','labelRu':'Уссурийск'},
     {'value':'Ust-Dzheguta','labelRu':'Усть-Джегута'},
     {'value':'Ust-Ilimsk','labelRu':'Усть-Илимск'},
     {'value':'Ust-Katav','labelRu':'Усть-Катав'},
     {'value':'Ust-Kut','labelRu':'Усть-Кут'},
     {'value':'Ust-Labinsk','labelRu':'Усть-Лабинск'},
     {'value':'Ustyuzhna','labelRu':'Устюжна'},
     {'value':'Ufa','labelRu':'Уфа'},
     {'value':'Ukhta','labelRu':'Ухта'},
     {'value':'Uchaly','labelRu':'Учалы'},
     {'value':'Uyar','labelRu':'Уяр'},
     {'value':'Fatezh','labelRu':'Фатеж'},
     {'value':'Theodosius','labelRu':'Феодосия'},
     {'value':'Fokino','labelRu':'Фокино'},
     {'value':'Fokino','labelRu':'Фокино'},
     {'value':'Frolovo','labelRu':'Фролово'},
     {'value':'Fryazino','labelRu':'Фрязино'},
     {'value':'Furmanov','labelRu':'Фурманов'},
     {'value':'Khabarovsk','labelRu':'Хабаровск'},
     {'value':'Khadyzhensk','labelRu':'Хадыженск'},
     {'value':'Khanty-Mansiysk','labelRu':'Ханты-Мансийск'},
     {'value':'Kharabali','labelRu':'Харабали'},
     {'value':'Kharovsk','labelRu':'Харовск'},
     {'value':'Khasavyurt','labelRu':'Хасавюрт'},
     {'value':'Khvalynsk','labelRu':'Хвалынск'},
     {'value':'Khilok','labelRu':'Хилок'},
     {'value':'Khimki','labelRu':'Химки'},
     {'value':'Hill','labelRu':'Холм'},
     {'value':'Kholmsk','labelRu':'Холмск'},
     {'value':'Khotkovo','labelRu':'Хотьково'},
     {'value':'Tsivilsk','labelRu':'Цивильск'},
     {'value':'Tsimlyansk','labelRu':'Цимлянск'},
     {'value':'Tsiolkovsky','labelRu':'Циолковский'},
     {'value':'Chadan','labelRu':'Чадан'},
     {'value':'Chaikovsky','labelRu':'Чайковский'},
     {'value':'Chapaevsk','labelRu':'Чапаевск'},
     {'value':'Chaplygin','labelRu':'Чаплыгин'},
     {'value':'Chebarkul','labelRu':'Чебаркуль'},
     {'value':'Cheboksary','labelRu':'Чебоксары'},
     {'value':'Chegem','labelRu':'Чегем'},
     {'value':'Chekalin','labelRu':'Чекалин'},
     {'value':'Chelyabinsk','labelRu':'Челябинск'},
     {'value':'Cherdyn','labelRu':'Чердынь'},
     {'value':'Cheremkhovo','labelRu':'Черемхово'},
     {'value':'Cherepanovo','labelRu':'Черепаново'},
     {'value':'Cherepovets','labelRu':'Череповец'},
     {'value':'Cherkessk','labelRu':'Черкесск'},
     {'value':'Chermoz','labelRu':'Чёрмоз'},
     {'value':'Blackhead','labelRu':'Черноголовка'},
     {'value':'Chernogorsk','labelRu':'Черногорск'},
     {'value':'Chernushka','labelRu':'Чернушка'},
     {'value':'Chernyakhovsk','labelRu':'Черняховск'},
     {'value':'Chekhov','labelRu':'Чехов'},
     {'value':'Chistopol','labelRu':'Чистополь'},
     {'value':'Chita','labelRu':'Чита'},
     {'value':'Chkalovsk','labelRu':'Чкаловск'},
     {'value':'Miracle','labelRu':'Чудово'},
     {'value':'Chulym','labelRu':'Чулым'},
     {'value':'Chusovoy','labelRu':'Чусовой'},
     {'value':'Chukhloma','labelRu':'Чухлома'},
     {'value':'Shagonar','labelRu':'Шагонар'},
     {'value':'Shadrinsk','labelRu':'Шадринск'},
     {'value':'Shawls','labelRu':'Шали'},
     {'value':'Sharypovo','labelRu':'Шарыпово'},
     {'value':'Sharya','labelRu':'Шарья'},
     {'value':'Shatura','labelRu':'Шатура'},
     {'value':'Mines','labelRu':'Шахты'},
     {'value':'Shakhunya','labelRu':'Шахунья'},
     {'value':'Shack','labelRu':'Шацк'},
     {'value':'Shebekino','labelRu':'Шебекино'},
     {'value':'Shelekhov','labelRu':'Шелехов'},
     {'value':'Shenkursk','labelRu':'Шенкурск'},
     {'value':'Shilka','labelRu':'Шилка'},
     {'value':'Shimanovsk','labelRu':'Шимановск'},
     {'value':'Shihans','labelRu':'Шиханы'},
     {'value':'Shlisselburg','labelRu':'Шлиссельбург'},
     {'value':'Shumerlya','labelRu':'Шумерля'},
     {'value':'Hype','labelRu':'Шумиха'},
     {'value':'Shuya','labelRu':'Шуя'},
     {'value':'Shchyokino','labelRu':'Щёкино'},
     {'value':'Shchelkino','labelRu':'Щёлкино'},
     {'value':'Schyolkovo','labelRu':'Щёлково'},
     {'value':'Shchigry','labelRu':'Щигры'},
     {'value':'Pike','labelRu':'Щучье'},
     {'value':'Elektrogorsk','labelRu':'Электрогорск'},
     {'value':'Elektrostal','labelRu':'Электросталь'},
     {'value':'Elektrougli','labelRu':'Электроугли'},
     {'value':'Elista','labelRu':'Элиста'},
     {'value':'Engels','labelRu':'Энгельс'},
     {'value':'Ertil','labelRu':'Эртиль'},
     {'value':'Yugorsk','labelRu':'Югорск'},
     {'value':'Yuzha','labelRu':'Южа'},
     {'value':'Yuzhno-Sakhalinsk','labelRu':'Южно-Сахалинск'},
     {'value':'Yuzhno-Sukhokumsk','labelRu':'Южно-Сухокумск'},
     {'value':'Yuzhnouralsk','labelRu':'Южноуральск'},
     {'value':'Yurga','labelRu':'Юрга'},
     {'value':'Yurievets','labelRu':'Юрьевец'},
     {'value':'Yuryev-Polsky','labelRu':'Юрьев-Польский'},
     {'value':'Yuryuzan','labelRu':'Юрюзань'},
     {'value':'Yukhnov','labelRu':'Юхнов'},
     {'value':'Yadrin','labelRu':'Ядрин'},
     {'value':'Yakutsk','labelRu':'Якутск'},
     {'value':'Yalta','labelRu':'Ялта'},
     {'value':'Yalutorovsk','labelRu':'Ялуторовск'},
     {'value':'Yanaul','labelRu':'Янаул'},
     {'value':'Yaransk','labelRu':'Яранск'},
     {'value':'Spring','labelRu':'Яровое'},
     {'value':'Yaroslavl','labelRu':'Ярославль'},
     {'value':'Yartsevo','labelRu':'Ярцево'},
     {'value':'Yasnogorsk','labelRu':'Ясногорск'},
     {'value':'Clear','labelRu':'Ясный'},
     {'value':'Yakhroma','labelRu':'Яхрома'}
   ];
   arrCityListRussia = await arrCityListRussia.map(city => {
     return {
       value: city.value,
       labelRu: city.labelRu,
       link: city.link,
       whoCreate: alexFox.id,
       region: russia[0].id,
       description: 'Описание отсутствует.'
     };
   });





   let resCityRussia = await City.createEach(arrCityListRussia).fetch();

   let resCountrySouthAmerica = await Country.createEach(arrCountrySouthAmerica).fetch();
   let resCountryNorthAmerica = await Country.createEach(arrCountryNorthAmerica).fetch();
   let resCountryAfrica = await Country.createEach(arrCountryAfrica).fetch();
   let resCountryAustralia = await Country.createEach(arrCountryAustralia).fetch();
   // console.log('resCountryEurasia: ', resCountryEurasia);
 */

  let ar = [];
  for (let y = 0; y < 5; y++) {
    let nm = await sails.helpers.strings.random('alphanumeric', 6);
    await ar.push({
      emailAddress: `${nm}@mail.ru`,
      fullName: nm,
      kennelAddress: nm,
      phone: await sails.helpers.strings.random('alphanumeric', 5),
      password: await sails.helpers.passwords.hashPassword(sails.config.custom.passwordSuperAdmin),
      preferredLocale: 'en'
    });
  }
  let createdUsers = await User.createEach(ar).fetch();
  sails.log(`Created ${createdUsers.length} user${createdUsers.length === 1 ? '' : 's'}.`);


  let kennelsArr = [
    {
      label: `Sasquehanna`,
      rightName: true,
      dateCreate: '2017-11-02T21:00:00.000Z',
      registerNumber: '000000',
      whoCreate: alexFox.id,
      continent: 1,
      country: 1,
      region: 5468685,
    },
    {
      label: `Zlato Dinastii`,
      rightName: true,
      dateCreate: '2017-11-02T21:00:00.000Z',
      registerNumber: '000000',
      whoCreate: alexFox.id,
      continent: 1,
      country: 1,
      region: 5468685,
    },
    {
      label: `Poale Ell`,
      rightName: true,
      dateCreate: '2017-11-02T21:00:00.000Z',
      registerNumber: '000000',
      whoCreate: alexFox.id,
      yourKennel:star.id,
      continent: 1,
      country: 1,
      region: 5468685,
    },
    {
      label: `Alfa Laval`,
      rightName: true,
      dateCreate: '2017-11-02T21:00:00.000Z',
      registerNumber: '000000',
      whoCreate: alexFox.id,
      continent: 1,
      country: 1,
      region: 5468685,
    },
    {
      label: `Olegro Katrin`,
      rightName: true,
      dateCreate: '2017-11-02T21:00:00.000Z',
      registerNumber: '000000',
      whoCreate: alexFox.id,
      continent: 1,
      country: 1,
      region: 5468685,
    },
    {
      label: `Laisand Island`,
      rightName: true,
      dateCreate: '2017-11-02T21:00:00.000Z',
      registerNumber: '000000',
      whoCreate: alexFox.id,
      continent: 1,
      country: 1,
      region: 5468685,
    },
  ];
  let createdKennels = await Kennel.createEach(kennelsArr).fetch();
  sails.log(`Created ${createdKennels.length} kennel${createdKennels.length === 1 ? '' : 's'}.`);
  const dogsArr = [
    {
      label: `Adam`,
      gender: 'sire',
      letter:'A',
      sale:false,
      dateBirth: moment('2017-11-02T21:00:00.000Z').format(),
      kennel: 'Poale Ell'
    },
    {
      label: `Ella`,
      gender: 'dam',
      letter:'E',
      sale:false,
      dateBirth: '2017-11-02T21:00:00.000Z',
      kennel: 'Sasquehanna'
    },
    {
      label: `De Lux Supernova`,
      gender: 'sire',
      letter:'D',
      sale:false,
      dateBirth: '2017-11-02T21:00:00.000Z',
      kennel: 'Alfa Laval'
    },
    {
      label: `Naruto`,
      gender: 'sire',
      letter:'N',
      sale:false,
      dateBirth: '2017-11-02T21:00:00.000Z',
      kennel: 'Olegro Katrin'
    },
    {
      label: `Neron`,
      gender: 'sire',
      letter:'N',
      sale:false,
      dateBirth: '2017-11-02T21:00:00.000Z',
      kennel: 'Zlato Dinastii'
    },
  ];

  dogsArr.map(dog => {
    dog.fullName=  `${dog.kennel} ${dog.label}`;
    dog.kennel = createdKennels.find(kennel => kennel.label === dog.kennel).id;
    let label = _.startCase(dog.label.toString().toLowerCase()).replace(/Fci\b/g, '(FCI)');

  });

  let createdDogs = await Dog.createEach(dogsArr).fetch();
  sails.log(`Created ${createdDogs.length} dog${createdDogs.length === 1 ? '' : 's'}.`);

  let poaleEll = await Kennel.findOne({label:'Poale Ell'});
  let userKennels =  await User.addToCollection(star.id, 'kennels', poaleEll.id);
  // let kennelUsers =  await Kennel.addToCollection(poaleEll.id, 'users', star.id);
  sails.log(`Created  ${userKennels} userKennels${userKennels === 1 ? '' : 's'}.`);
  // sails.log(`Created  ${kennelUsers} kennelUsers${kennelUsers === 1 ? '' : 's'}.`);
  // Нужно создать индекс по полям предков в DB, чтобы включить быстрый поиск по узлам предков:
  // db.categories.createIndex( { ancestors: 1 } )
  // let categories = await  Category.createEach( [{ name: "MongoDB", ancestors: [ "Books", "Programming", "Databases" ], parent: "Databases" },
  //   { name: "dbm", ancestors: [ "Books", "Programming", "Databases" ], parent: "Databases" },
  //   { name: "Databases", ancestors: [ "Books", "Programming" ], parent: "Programming" },
  //   { name: "Languages", ancestors: [ "Books", "Programming" ], parent: "Programming" },
  //   { name: "Programming", ancestors: [ "Books" ], parent: "Books" },
  //   { name: "Books", ancestors: [ ], parent: null }]).fetch();
  //
  // let tree = await  Tree.createEach( [{ name: "MongoDB", ancestors: [ "Books", "Programming", "Databases" ], parent: "Databases" },
  //   { name: "dbm", ancestors: [ "Books", "Programming", "Databases" ], parent: "Databases" },
  //   { name: "Databases", ancestors: [ "Books", "Programming" ], parent: "Programming" },
  //   { name: "Languages", ancestors: [ "Books", "Programming" ], parent: "Programming" },
  //   { name: "Programming", ancestors: [ "Books" ], parent: "Books" },
  //   { name: "Books", ancestors: [ ], parent: null }]).fetch();

  // sails.log(`Created ${tree.length} tree${tree.length === 1 ? '' : 's'}.`);

  /* let airports  = await  Airports.createEach( [
     {"airport" : "JFK", "connects" : [ "BOS", "ORD" ] },
     {"airport" : "BOS", "connects" : [ "JFK", "PWM" ] },
     {"airport" : "ORD", "connects" : [ "JFK" ] },
     {"airport" : "PWM", "connects" : [ "BOS", "LHR" ] },
     {"airport" : "LHR", "connects" : [ "PWM" ] }]).fetch();

   sails.log(`Created ${airports.length} airport${airports.length === 1 ? '' : 's'}.`);

   let travelers   = await  Travelers.createEach( [
     {"name" : "Dev", "nearestAirport" : "JFK" },
     {"name" : "Eliot", "nearestAirport" : "JFK" },
     {"name" : "Jeff", "nearestAirport" : "BOS"}
   ]).fetch();

   sails.log(`Created ${travelers.length} traveler${travelers.length === 1 ? '' : 's'}.`);
 */
  // for (let y = 0; y < 100; y++) {
  //
  //   let nm = await sails.helpers.strings.random("alphanumeric", 6);
  //   nm = await User.create({
  //     emailAddress: `${nm}@mail.ru`,
  //     fullName: nm,
  //     kennelAddress: nm,
  //     phone: await sails.helpers.strings.random("alphanumeric", 6),
  //     password: await sails.helpers.passwords.hashPassword(sails.config.custom.passwordSuperAdmin),
  //     preferredLocale: 'en'
  //   }).fetch();
  //
  //   await User.addToCollection(nm.id, 'groups', group2.id);
  // }

  // В БУДУЩЕМ: Решить что с эти делать
  // Create some things
  /* await Thing.createEach([
    {owner: ryanDahl.id, label: 'Сладкая дрель'},
    {owner: ryanDahl.id, label: 'Капкан на куницу'},
    {owner: ryanDahl.id, label: 'Моторная лодка'},
    {owner: alexFox.id, label: 'Красный рассвет'}
  ]).fetch(); */

  /*  await Litter.createEach([
      {owner: alexFox.id,label: 'a', born: new Date(2016, 3, 10)},
      {owner: alexFox.id,label: 'b', born: new Date(2017, 10, 3)},
      {owner: ryanDahl.id,label: 'c', born: new Date(2008, 2, 15)},
      {owner: ryanDahl.id,label: 'd', born: new Date(2010, 5, 21)}]).fetch();*/


  // Save new bootstrap version
  await sails.helpers.fs.writeJson.with({
    destination: bootstrapLastRunInfoPath,
    json: {
      lastRunVersion: HARD_CODED_DATA_VERSION,
      lastRunAt: Date.now()
    },
    force: true
  })
    .tolerate((err) => {
      sails.log.warn('По какой-то причине не удалось записать загрузочную версию файла .json. Это может быть результатом проблемы с настроенными вами путями или, если вы работаете, ограничения хостинг-провайдера, связанного с `pwd`. В качестве обходного пути попробуйте обновить app.js, чтобы явно передать в `appPath: __dirname` вместо того, чтобы полагаться на` chdir`. Текущий sails.config.appPath: `' + sails.config.appPath + '`.  Полная информация об ошибке: ' + err.stack + '\n\n(Продолжим в любом случае в этот раз...)');
    });

};
